#S-BO-001=\u66f4\u65b0\u5de5\u5355\u8868\u5931\u8d25\uff01
#S-BO-002=\u6839\u636e\u5458\u5de5\u6807\u8bc6\u67e5\u8be2\u4e0d\u5230\u5458\u5de5
S-BO-003=Rule template has been referenced by rule template instance
S-BO-004=Rule template has been referenced by rule template instance
S-BO-005=Node
S-BO-006=Process Flow
S-BO-007=The same process flow template already exists, please re-select again.
S-BO-008=The same function component already exists, please re-select again.
S-BO-009=There is no work order.
S-BO-010=Fail to delete {0}, because it has been referenced by {1}.
S-BO-011=The same {0} already exists, please input again.
S-BO-012=The dispatch order is empty.
S-BO-013=The same feature already exists, please select again.