REPORT.ROLE_CODE=Role Code 
REPORT.ROLE_DESC=Role Description
REPORT.ROLE_ID=Role ID
REPORT.ROLE_MGR=Role Management
REPORT.ROLE_NAME=Role Name
REPORT.IS_LOCKED=Is Locked
REPORT.REPORT_ROLE=Report Role

REPORT.REPORT_DIRECTORY=Report Directory
REPORT.DIR_NAME=Directory Name
REPORT.ROOT_DIR=Root Directory
REPORT.REPORT_INFORMATION=Report Base Information
REPORT.REPORT_NAME=Report Name
REPORT.REPORT_FILE_PATH=Layout File Path
REPORT.SERVICE_NAME=Service Name
REPORT.REPORT_COND_LIST=Report Condition List
REPORT.PARAM_NAME=Parameter Name
REPORT.PARAM_FIELD_NAME=Parameter Field Name
REPORT.PARAM_TYPE=Parameter Type
REPORT.NULLABLE=Nullable
REPORT.DEFAULT_VALUE=Default Value
REPORT.REPORT_PURVIEW=Purview
REPORT.POP_EDIT=PopEdit
REPORT.DISPLAY_FIELD=Display Field
REPORT.VALUE_FIELD=Value Field
REPORT.REPORT=Report
REPORT.HINT_AUTHORIZATION_SUCC=Succeed in authorization.
REPORT.ROLE=Role

COMMON.PRIMARY_NE=Primary NE
COMMON.HINT_QRY_NO_RECORD=No results were found.
COMMON.COMPANY=Company
COMMON.STAFF_NAME=Staff Name
COMMON.STAFF_CODE=Staff Code
COMMON.STAFF_INQUIRY=Staff Query
REPORT.DOWN_LOAD=Download

REPORT.CONDITION_DETAIL=Report Condition Detail
REPORT.REVIEW=Report Review
REPORT.EXIST_SAME_PARAM=The same parameter name of the report already exists. Please input again.
REPORT.FAIL_CONVERT_SWF=The PDF file is too larger to be converted to SWF. Please Download the PDF file!