package com.sts.sinorita.dto.response.accountconfig;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class QryBalanceTypeWithMVNOResponseDto {
    private Integer balType;
    private String balTypeName;
    private Integer acctResId;
    private String acctResName;
    private Character isCurrency;
    private String comments;
    private Long creditLimit;
    private Long maxValue;
    private Character refillable;
    private String stdCode;
    private Character paymentForce;
    private Integer parentAcctResId;
    private Character isFreeUnit;
    private Integer value;
    private Integer rum;
    private Integer defaultAcctItemType;
    private Integer storeUnit;
    private String parentAcctResName;
    private String acctItemTypeName;
    private Integer spId;
    private Integer unitTypeId;
    private Long unitPrecision;
    private String unitTypeName;
    private Integer ratioMoney;
    private Integer ratioPrecision;
    private Integer priority;
    private String extendRule;
    private String extendRuleName;
    private Integer maxAdjustValue;
    private Integer maxChgValue;
    private Integer maxExpDate;
    private Character resetZero;
    private String resetZeroName;
    private Integer acmThreshold;
    private String acmType;
    private Character acmUnit;
    private String acmUnitName;
    private Integer acmAmount;
    private Integer ceilLimit;
    private Integer floorLimit;
    private Integer dailyCeilLimit;
    private Integer dailyFloorLimit;
    private Integer gracePeriod;
    private Integer usageType;
    private Character rewardFlag;
    private Character unlimitedFlag;
    private Integer maxRollover;
    private Integer adjustType;
    private Character balanceAggregation;
    private String category;
    private Character rolloverFlag;
    private Integer dayThreshold;
    private Integer weekThreshold;
    private Integer monthThreshold;
    private Integer dayCount;
    private Integer weekCount;
    private Integer monthCount;
    private Integer minResidualBal;
    private Integer maxAllowed;
    private Integer minAllowed;
    private Integer transferFactor;
    private Character overdraftFlag;
    private Integer reservePercentage;
    private Character freeFlag;
    private Character adjustFlag;
    private Character balCategory;
    private Character clearFlag;
    private Integer clearDays;
    private Character customerFlag;
}
