ORANGE_BL_00001=Can not find any account balance type by standard code {0}.
ORANGE_BL_00002=The operation is only for the prepaid account.
ORANGE_BL_00003=The operation is only for the postpaid account.
ORANGE_BL_00004=The amount should be positive.
ORANGE_BL_00005=The amount should be negative.
ORANGE_BL_00006=Can not find any contact channel by id {0}.
ORANGE_BL_00007=The subscriber has not ordered dependent product of iSMS.
ORANGE_BL_00008=The subscriber has ordered dependent product of CII.
ORANGE_BL_00009=The contact channel id is required.
ORANGE_BL_00010=The max query duration is {0} days.
OCI-S-ACT-00034=Last loan install records are not paid off.
OCI-S-ACT-00035=The config OCI_LOAN_INSTALL_PERCENT is missing or wrong.
OCI-S-ACT-00036=No debit bal records to split.