#Error code&message for BPM
BFM-BPM-00001=The expired date must be later than the effective date.
BFM-BPM-00002=The version name already exists.
BFM-BPM-00003=Time conflict error. The period between effective date and expired date overlaps another version.
BFM-BPM-00004=Errors occurred while parsing bpmn xml.
BFM-BPM-00005=The value of 'tempId' is not equals to the value of attribute 'id' in element 'process' in bpmn xml, 'tempId'={0}, 'process id'={1}. 
BFM-BPM-00010=Cannot find execution for id {0}.
BFM-BPM-00011=This activity doesn't accept 'complete' action, activity type is {0}.
BFM-BPM-00020=Fail to start process.
BFM-BPM-00021=Fail to execute service task.
BFM-BPM-00022=Fail to terminate process.
BFM-BPM-00023=Fail to commit task.
BFM-BPM-00024=The process code already exists.
BFM-BPM-00025=The method {0} doesn't exist.
BFM-BPM-00030=Cannot find the expected acitivty instance in execution.
#EForm
BFM_EFORM_001=The same catalog name exists. Please input again.
#Metadata
BFM-001=Module can't have same name in the same parent module!
BFM-002=This module can't be deleted because of child modules!
BFM-MD-001=Catalog can't have same name in the same parent catalog!
BFM-MD-002=This catalog can't be deleted because of child catalogs!
BFM-MD-003=This catalog can't be deleted because of child BusinessObject!
BFM-MD-004=This catalog can't be deleted because of child TechnicalObject!
BFM-MD-005=BusinessObject can't have same access name.
BFM-MD-006=BusinessObject can't have same name in the same module.
BFM-MD-007=BusinessObject can't have same name in the same catalog.
BFM-MD-008=BusinessObject item can't have same name or access name in the same BO.
BFM-MD-009=Method parameter can't have same name or sequence!
BFM-MD-011=TechnicalObject can't have same access name.
BFM-MD-012=TechnicalObject can't have same name in same module!
BFM-MD-013=TechnicalObject can't have same name in same catalog!
BFM-MD-014=Technical item can't has same name or accessName in the same object!
BFM-MD-015=Business Object can't be deleted because of child properties!
BFM-MD-016=Fail to delete the business object, because it has been referenced by property.
BFM-MD-050=The same message code exists. Please input again.
BFM-MD-051=Fail to delete the business message, because it has been referenced by rule output.
BFM-MD-020=There is a exist trigger with datasoure item.
BFM-MD-060=BusinessObject method can't have same method.
BFM-MD-061=This Business Object has referenced by Rule.
BFM-MD-062=The table is not in the DSN. Please input again.
BFM-MD-070=This Business Object Item has referenced by Rule Chain Member.
BFM-MD-071=There can be only product version to do the operation
BFM-MD-072=Please select a project
#Rule
BFM-RL-00101=The version already exists.
BFM-RULE-1099={0}
BFM-RULE-1101=Rule Name already exists.
BFM-RULE-1102=Rule Code already exists.
#Event
BFM_EVENT_01000=Duplicate event code.
#Tools
BFM_TLS_00100=Fail to export data.
BFM_TLS_00101=Fail to import data.
BFM_TLS_00102=The argument FILE_CONTENT or FILE_ID is required for importing data.
BFM_TLS_00103=Cannot find the import file in database.
BFM_TLS_00104=Compress error.
BFM_TLS_00105=Decompress error.
BFM_TLS_00110=An error occurred while importing xml! Please check the xml file you uploaded and try again later.
BFM_TLS_00120=Fail to parse snapshot.
BFM_TLS_00121=Fail to decompress snapshot content from byte array to string.
BFM_TLS_00122=Fail to compress snapshot content from string to byte array.
BFM_TLS_00123=Write file error.
BFM_TLS_00124=Read file error.
#AMP
BFM-AMP-00001=Component name already exists.
BFM-AMP-00002=Cannot disable the application which is referenced by some business components.
BFM-AMP-00003=Entity name already exists.
BFM-AMP-00004=Cannot disable the business component which is referenced by some function components.
BFM-AMP-00005=Cannot disable the business component which is referenced by some applications.
BFM-AMP-00006=Cannot disable the function component which is referenced by some business components.
BFM-AMP-00007=Cannot disable the entity which is referenced by applications or business components.
BFM-AMP-00008=An component implementation with same prodFlag(product/project) already exists.
BFM-AMP-00100=The parameter is required and cannot be empty.
BFM-AMP-00101=Fail to get value from the function component. Cannot find getter method for field.
BFM-AMP-00102=An error occurred while invoking the method setValue().
BFM-AMP-00103=Fail to set value to the function component. Cannot find setter method for field.
BFM-AMP-00130=Fail to get field value from entity in DataContext.
BFM-AMP-00131=The entity object is not a valid instance of the entity class in configuration.
BFM-AMP-00132=Fail to set field value to entity in DataContext.
BFM-AMP-00133=Fail to get session attribute.
BFM-AMP-00110=Cannot execute component {0}: No definition found!
BFM-AMP-00111=The function component must be running within a business component.
BFM-AMP-00112=The entity object is not a valid instance of the entity class in configuration.
BFM-AMP-00113=Fail to instantiate the component class to a java object.
BFM-AMP-00120=Call event decision error.
BFM-AMP-00121=Unable to evaluate exit expression in message handler.
BFM-AMP-00200=TimeSeries period error.
BFM-AMP-00210=Unsupported component type.
BFM-AMP-00211=Invoke component error.
BFM-AMP-00212=Group name already exists. Please input again.
BFM-AMP-99999=System error. Please contact the administrator.

#UI
BFM-UI-00001=The same code exists. Please input again.
#CONTROL
BFM-CONTROL-001=There is no decision event relevant to message {}.
BFM-CONTROL-002=Unable to initialize business object {}.
BFM-CONTROL-003=No available process template to start! Please check decision event relevant to message {}.
BFM-CONTROL-004=CommonData is time out.
BFM-CONTROL-005=Process task does not support {} event.
BFM-CONTROL-006=Failed to resume bo.
#EVENT
BFM-EVENT-00001=The event code exists. Please input again.

S-PTF-11099=The same feature code exists. Please input again.