S-DOMAINFRAME-00001=Fail to instantiate the class [{0}].
S-DOMAINFRAME-00002=Fail to get the field value.
S-DOMAINFRAME-00003=Fail to set the field value.
S-DOMAINFRAME-00004=Fail to get the spring bean, bean id is [{0}].
S-DOMAINFRAME-00005=Fail to clone the entity feature, class is [{0}].
S-DOMAINFRAME-00006=Fail to get the entity, entity name is [{0}].
S-DOMAINFRAME-00007=Fail to get the value object, value object name is [{0}].
S-DOMAINFRAME-00008=Fail to get the factory, factory name is [{0}].
S-DOMAINFRAME-00009=Fail to get the repository, repository name is [{0}].
S-DOMAINFRAME-000010=Fail to get the domain service, domain service name is [{0}].
S-DOMAINFRAME-000011=Fail to get the application service, application service name is [{0}].