#Created by JInto - www.guh-software.de
#Mon May 04 14:16:52 CST 2009

#Exception in Runtime
S_MDR_0001=Fail to create instance for class {0}
S_MDR_0002=Run-time mode has been set
S_MDR_0003=Fail to resolve class {0}
S_MDR_0004=Inactive bcImpl {0}
S_MDR_0005=Project code is required, bcImpl = {0}
S_MDR_0006=Illegal value [{0}] in type [{1}]
S_MDR_0007=Illegal element, no implement found
S_MDR_0008=Illegal element, no compId defined for accessName {0}, type {1}
S_MDR_0009=Illegal compId {0}
S_MDR_0010=No compId defined
S_MDR_0011=can't not load from database in DT mode
S_MDR_0012=no mdr session has been created
S_MDR_0013=more than one mdr session have been created
S_MDR_0014=baselineId has been set for component {0}, current {1}, setting {2} 
S_MDR_0015=fail to parse date {0}
S_MDR_0016=new component must not be migrate, id : {0}
S_MDR_0017=duplicate id : {0}
S_MDR_0018=item is not a root, name : {0}
S_MDR_0019=tree item has already exist in tree, full name : {0}
S_MDR_0020=tree item does not exist in tree, full name : {0}
S_MDR_0021=fail to add path to tree : {0}
S_MDR_0022=a migrate component should no be imported. id : {0}, source : {1}
S_MDR_0023=bfm data does not exist, type [{0}], data [{1}]

#Exception in Cache
S_MDR_0101=Fail to find category {0} in cache
S_MDR_0102=Unsupported key {0} in category {1}
S_MDR_0103=Duplicated data on index {0}, old data {1}, new data {2}
S_MDR_0104=Fail to find component {0} in cache. type {1}

#Exception when transform
S_MDR_0201=Fail to transform component : type {0}, id: {1} 
S_MDR_0202=Fail to transform xml document to string : id {0}
S_MDR_0203=Fail to save file [{0}] 
S_MDR_0204=Fail to clean file [{0}] 
S_MDR_0205=Fail to validate ,source : [{0}] 

#Exception when loading xml in mdr
S_MDR_0301=Fail to load comp {0}
S_MDR_0302=Fail to handle file {0}
S_MDR_0303=Fail to load comp type {0}

#Exception when import
S_MDR_0401=too many component found in db : id {0}, source: {1} 
S_MDR_0402=Fail to import component : id {0}, source: {1} 

#Exception when plugin
S_MDR_0501={0} Value can't be empty 