CONFIG.BSN_CFG_ITEM=Business Configuration Item
CONFIG.MODULE_NAME=Module Name
CONFIG.MODULE_CODE=Module Code
CONFIG.CFG_ITEM_CODE=Item Code
CONFIG.CFG_ITEM_NAME=Item Name
CONFIG.CFG_ITEM_COMMENTS=Item Remarks
CONFIG.CODE=Code
CONFIG.NAME=Name
CONFIG.COMMENTS=Description
CONFIG.CHINESE_COMMENTS=Chinese Description
CONFIG.MOD_HIS_QUERY=Modify History
CONFIG.NORMAL_PARAM=General Parameters
CONFIG.PARAM_NAME=Parameter Name
CONFIG.PARAM_VALUE=Parameter Value
CONFIG.PARAM_CODE=Parameter Code
CONFIG.ADD_FEATURE_VALUE=Add feature Value
CONFIG.PROMPT_HIDDEN_FEATURES=Prompt-hidden Features

CONFIG.DEFAULT_PARAM_VALUE=Default Value
CONFIG.GRID_PARAM=Grid Parameters
CONFIG.CFG_ITEM=Configuration item
CONFIG.CFG_STATE=, state:
CONFIG.NOT_EXSIT=not exist
CONFIG.PARAM_MOD_TIP= parameters modified as follows:\n

CONFIG.NEW_VALUE=New Value
CONFIG.OLD_VALUE=Old Value

CONFIG.PARAM_VALUE_ID=Parameter Value Id
CONFIG.UPLOAD_FILE=File Upload
CONFIG.ANALYSE_FILE=Analysis File
CONFIG.ANALYSE_FILE_LOG=Log
CONFIG.ANALYSE_FILE_EMPTY=Upload file is mandatory.
CONFIG.SEARCH=Search
CONFIG.MAX_VALUE=Maximum Value
CONFIG.MIN_VALUE=Minimum Value
CONFIG.MODIFIER=Modifier
CONFIG.UPDATE_TIME=Update Time

CONFIG.MENU_NAME=Menu Name
CONFIG.CFG_ITEM_PARAM_IMPORT=Import Configuration Item
CONFIG.HINT_IMPORT_DATA_SUCCESS=Succeed in importing data.
CONFIG.HINT_UPLOAD_FILE=Please upload file.
CONFIG.HINT_INPUT_WORD=Please input the search word.
CONFIG.HINT_SELECT_CFG_ITEM=Please select at least one item.
CONFIG.HINT_ANALYSE_FILE_TIP=\n Note: Those configuration items and parameters which do not exist will be filtered out, without saving to the database.

CONFIG.QRY_NULL_PARAM_VALUE=Unconfigured
CONFIG.VISIBLE=Visible
CONFIG.INVISIBLE=Invisible
CONFIG.MODIFIABLE=Modifiable
CONFIG.UNMODIFIABLE=unmodifiable
CONFIG.CHANGE_STATE_VISIBLE=Toggle Visible State
CONFIG.CHANGE_STATE_MODIFIABLE=Toggle Modifiable State
CONFIG.VISIBLE_STATE=Visible State
CONFIG.MODIFY_STATE=Modifiable State
CONFIG.MODIFY=Modify

CONFIG.HINT_ANALYSE_FILE_HEADER=All configuration items are described as follow\uff1a\n
CONFIG_ITEM_PARSE_LOG=Configuration Item [NAME={0}, CODE={1}]\n
CONFIG_ITEM_PARSE_LOG_ADD=Configuration Item [NAME={0}, CODE={1}] [<FONT COLOR='#FF0000'>Not Existed</FONT>]\n
CONFIG_ITEM_PARSE_LOG_MOD=Configuration Item [NAME={0}, CODE={1}] [<FONT COLOR='#FF0000'>Modified</FONT>]\n

CONFIG_ITEM_PARAM_PARSE_LOG=\tParameter: [CODE={0}], [VALUE={1}].\n
CONFIG_ITEM_PARAM_PARSE_LOG_ADD=\tParameter: [CODE={0}], [VALUE={1}]. [<FONT COLOR='#FF0000'>Not Existed</FONT>]\n
CONFIG_ITEM_PARAM_PARSE_LOG_MOD=\tParameter: [CODE={0}], [NEW VALUE={1}], [OLD VALUE={2}]. [<FONT COLOR='#FF0000'>Modified</FONT>]\n

CONFIG_ITEM_PARAM_VALUE_PARSE_LOG=\t\t Parameter Value: [VALUE ID={0}], [VALUE={1}].\n
CONFIG_ITEM_PARAM_VALUE_PARSE_LOG_ADD=\t\t Parameter Value: [VALUE ID={0}], [VALUE={1}]. [<FONT COLOR='#FF0000'>Not Existed</FONT>]\n
CONFIG_ITEM_PARAM_VALUE_PARSE_LOG_MOD=\t\t Parameter Value: [VALUE ID={0}], [NEW VALUE={1}], [OLD VALUE={2}]. [<FONT COLOR='#FF0000'>Modified</FONT>]\n
CONFIG.SHOW_FEATURES=Show Features    
CONFIG.FILTER_FEATURES=Filter Features
CONFIG.FEATURE_CODE=Feature Code
CONFIG.SHOW_VALUES=Show Values

BFM.BIZ_CACHE_MODEL_NAME=Model Name
BFM.BIZ_CACHE_CACHE_NAME=Cache Name
BFM.BIZ_CACHE_CACHE_PERIOD=Cache Period
BFM.HINT_CACHE_UNIT_NULL=Please select the unit of cache period.
BFM.HINT_CACHE_NUMBER_INT=The cache period should be integer greater than 0.Please input again.
BFM.HINT_CACHE_NUMBER_NULL=Please input the cache period number.
BFM.BFM_BIZ_CACHE=BFM BIZ CACHE
BFM.HINT_CACHE_RESULT_SUCESS={0} cache has been cleared successfully.
BFM.HINT_CACHE_RESUTL_FAILED={0} failed to clear the cache!

CONFIG.PARAM_VALUE_SPECIALCHAR=Parameter values contain special characters (& <> "'), Make sure to continue!