MEMO.EVENT_COLOR=Event Color
MEMO.ALARM_TYPE=Alarm Type
MEMO.NONE=None
MEMO.SPECIFIED_TIME=Specified time
MEMO.SAME_TIME_EVERYDAY=Same time everyday
MEMO.WEEK_ALARM=Week Alarm
MEMO.EFFECT_TIME=The change takes effect next time you login.
MEMO.ADD_EVENT=Add a new Days/Time Event
MEMO.EDIT_EVENT=Edit a new Days/Time Event
MEMO.MONDAY=Monday
MEMO.TUESDAY=Tuesday
MEMO.WEDNESDAY=Wednesday
MEMO.THURSDAY=Thursday
MEMO.FRIDAY=Friday
MEMO.SATURDAY=Saturday
MEMO.SUNDAY=Sunday
MEMO.HINT_MOD_SUCCESS=Succeed in modifying the memo.
MEMO.HINT_ADD_SUCCESS=Succeed in adding the memo.