####\u516c\u7528\u8d44\u6e90
BUSIORDER.OK=OK
BUSIORDER.SAVE=Save
BUSIORDER.CANCEL=Cancel
BUSIORDER.RESET=Reset
BUSIORDER.QUERY=Query
BUSIORDER.ADD=New
BUSIORDER.DELETE=Delete
BUSIORDER.EDIT=Edit
BUSIORDER.CODE_NAME=Code Name
BUSIORDER.NAME=Name
BUSIORDER.DETAIL=Detail
BUSIORDER.HINT_SEARCH_MATCH_NULL=No matching items were found.
BUSIORDER.HINT_ADD_SUCCESS=Succeed in adding {0}.
BUSIORDER.HINT_MOD_SUCCESS=Succeed in modifying {0}.
BUSIORDER.HINT_DEL_SUCCESS=Succeed in deleting {0}.
BUSIORDER.STAFF=Staff
BUSIORDER.ORG=Organization
BUSIORDER.USERGROUP=UserGroup
BUSIORDER.STAFF_JOB=Staff Job
BUSIORDER.EXPORT=Export
BUSIORDER.YES=Yes
BUSIORDER.NO=No
BUSIORDER.HINT_NOT_RECORD=No results were found.
BUSIORDER.REMARKS=Remarks
#######################################################################################

BUSIORDER.RELEASE_ORDER=Release Work Order
BUSIORDER.ASSIGN_NEXT_OPER=Assign Next Operator.
BUSIORDER.COMMENTS=Remarks
BUSIORDER.RELEASE=Release
BUSIORDER.ADD_WORK_ORDER=Add Work Order
BUSIORDER.ADD_WOKR_ORDER_SUCCESS=Succeed in adding work order.
BUSIORDER.OPER_MAN=Operator
BUSIORDER.AUDIT=Audit
BUSIORDER.AUDIT_YES=Pass
BUSIORDER.AUDIT_NO=Reject
BUSIORDER.AUDIT_SUCCESS=Succeed in auditing work order.
BUSIORDER.ORG_AND_STAFF=Organization and Staff
BUSIORDER.ASSIGN_BEHIND_ACTITY=Assign Next Activity
BUSIORDER.NODE_ID=Node ID
BUSIORDER.NODE_CODE=Node Code
BUSIORDER.NODE_NAME=Node Name
BUSIORDER.CODE=Code
BUSIORDER.ASSIGN_NODE=Assign Node
BUSIORDER.RELEASE_SUCCESS=Succeed in releasing the work order, do you want to close the window?
BUSIORDER.PLS_ASSIGN_NEXT_OPER = Please assign the next operator.
BUSIORDER.PLS_ASSIGN_NEXT_NODE = Please assign the next node.
BUSIORDER.ASSIGN_SUCCESS = Succeed in assigning the next operator.
BUSIORDER.CHK_ORG_STAFF_ONLY=Please do not choose the organization and staff at the same time.
BUSIORDER.ORG_STAFF_TITLE = Select Organization or Staff
BUSIORDER.ORG_STAFF_USERGROUP_TITLE = Select Organization or Staff or UserGroup
BUSIORDER.PLE_SEL_ORG=Please select the organization.
BUSIORDER.ISNOT_DISPATCH_SELF=Please do not dispatch to yourself.
BUSIORDER.DISPATCH=Dispatch
BUSIORDER.SUSPEND = Suspend
BUSIORDER.UNSUSPEND=Activate
BUSIORDER.CHECKOUT=Check Out
BUSIORDER.CHECKIN=Check In
BUSIORDER.WORK_ORDER_STATE=State
BUSIORDER.EXCEPTION_REASON=Exception Reason
BUSIORDER.DISPATCH_SUCCESS=Succeed in dispatching the work order.
BUSIORDER.CHECK_IN_SUCCESS=Succeed in checking in the work order.
BUSIORDER.CHECK_OUT_SUCCESS=Succeed in Checking out the work order.
BUSIORDER.SUSPEND_SUCCESS=Succeed in suspending the work order.
BUSIORDER.UNSUSPEND_SUCCESS=Succeed in activating the work order.
#BUSIORDER.WORK_ORDER_STATE=\u5de5\u5355\u72b6\u6001
BUSIORDER.WORK_ORDER_STATE_NAME=State Name
BUSIORDER.WORK_ORDER_COMMENT=Remarks
BUSIORDER.PLS_SEL_WORK_ORDER_STATE=Please select work order state.
BUSIORDER.PLS_SEL_MANUAL_FUNC_TO_DEL=Please select the node manual function to be deleted.
BUSIORDER.DELETE_MANUAL_FUNC_SUCCESS=Succeed in deleting the node manual function.
BUSIORDER.DELETE_MANUAL_FUNC_FAIL=Fail to Delete the node manual function.
BUSIORDER.SEQ_REPEAT=The display sequence can not be duplicate, please input again.
BUSIORDER.PLS_SEL_ACTIVITY_NODE=Please select the activity node.
BUSIORDER.ADD_MANUAL_FUNC_SUCCESS=Succeed in adding the node manual function.
BUSIORDER.ADD_MANUAL_FUNC_FAIL=Fail to add the node manual function.
BUSIORDER.MOD_MANUAL_FUNC_SUCCESS=Succeed in modifying the manual function.
BUSIORDER.MOD_MANUAL_FUNC_FAIL=Fail to modify the manual function failure.

BUSIORDER.PLS_SEL_MANUAL_FUNCT_NODE=Please select node manual function.
BUSIORDER.ISNOT_HAVE_WORK_ORDER_ID=There is no work order ID in the passed parameter.
BUSIORDER.PLSSEL_DISP_ORG_OR_STAFF=Please select the staff or organization to dispatch.
##WorkOrderDetailActionWindow.mxml
BUSIORDER.WORK_ORDER_ACTION_ID=Work Order Action ID
BUSIORDER.WORK_ORDER_ID=Work Order ID
BUSIORDER.NODE_FUNCTION_ID=Node Function ID
BUSIORDER.NODE_FUNCTION_NAME=Node Function Name
BUSIORDER.ACTION_TITLE=Action Title
BUSIORDER.PROCESS_ORDER=Process Order
BUSIORDER.CREATE_PARTY_TYPE=Create Party Type
BUSIORDER.CREATE_PARTY_CODE=Create Party Code
BUSIORDER.REASON_ID=Reason ID
BUSIORDER.ASSIGN_PARTY_TYPE=Assign Party Type
BUSIORDER.ASSIGN_PARTY_CODE=Assign Party Name
BUSIORDER.DEAL_DETAIL=Deal Detail
BUSIORDER.CREATE_DATE=Created Time
BUSIORDER.CREATE_ON=Created On
BUSIORDER.ORG_ID=Organization ID
BUSIORDER.WO_ACTION_ATTR_ID=Feature ID
BUSIORDER.WO_ACTION_ATTR_VALUE=Feature Value
BUSIORDER.WORK_ORDER_ACTION_ATTA_DETAIL=Attachment Detail
BUSIORDER.ATTA_ATTACHMENT_NAME=Attachment Name
BUSIORDER.ATTA_ATTACHMENT_URL=Attachment URL
BUSIORDER.WORK_ORDER_ACTION_ATTR=Work Order Action Extended Information
##WorkOrderDetailWindow.mxml
BUSIORDER.WORK_ORDER_CODE=Work Order Code
#BUSIORDER.WORK_ORDER_STATE=\u72b6\u6001
BUSIORDER.WORK_ORDER_STATE_DATE=State Time
BUSIORDER.FINISH_LIMIT_DATE=Finish Limit Time
BUSIORDER.WARN_LIMIT_DATE=Warn Limit Time
BUSIORDER.FINISH_DATE=Finish Time
BUSIORDER.WORK_ORDER_PARTY_TYPE=Party Type
BUSIORDER.WORK_ORDER_PARTY_CODE=Party Code
BUSIORDER.WORK_ORDER_CHECKIN_DATE=Check In Date
BUSIORDER.WORK_ORDER_CHECKOUT_DATE=Check Out Date
BUSIORDER.BOOKING_START_DATE=Booking Start Date
BUSIORDER.BOOKING_END_DATE=Booking End Date
BUSIORDER.WORK_ORDER_CONTENT=Work Order Remarks
BUSIORDER.REASON_INFO=Exception Reason
##TaskCenter.mxml
BUSIORDER.TASK_CENTER=Work Order Task Center
BUSIORDER.PREPEND_TASK=Prepend Task
BUSIORDER.ALL_TASK=All Task

BUSIORDER.FINISH_DATE_FROM=Finish Date From
BUSIORDER.FINISH_DATE_TO=To
BUSIORDER.STATE_DATE_FROM=Dispatch Date From
BUSIORDER.STATE_DATE_TO=To
BUSIORDER.FINISH_DATE_PER_FROM=Finish Date From
BUSIORDER.FINISH_DATE_PER_TO=Finish Date To
BUSIORDER.STATE_DATE_PER_FROM=Dispatch Date From
BUSIORDER.STATE_DATE_PER_TO=Dispatch Date To
BUSIORDER.WORK_ORDER_DEAL=Work Order Deal
BUSIORDER.CREATE_PARTY_NAME=Create Party Name
BUSIORDER.ACTION_ATTRIBUTE=Action Feature
BUSIORDER.NODE_FUNCTION=Node Function
BUSIORDER.WORK_ORDER_ACTION_DETAIL=Work Order Action Detail
BUSIORDER.SELF_WORK_ORDER=Self Work Order
BUSIORDER.QRY_RESULT_IS_NULL=No results were found.
BUSIORDER.STAFF_PREPEND_TASK=Prepend Task of Staff
BUSIORDER.ORG_PREPEND_TASK=Prepend Task of Organization
BUSIORDER.NO_TIME_OUT_TASK=No Time Out Task({0})
BUSIORDER.WARNING_TASK=Warning Task({0})
BUSIORDER.OUT_TIME_TASK=Out Time Task({0})


######################WfNodeManualFuncCfg#################################################################
BUSIORDER.SELECT_NODE=Select Node
BUSIORDER.NODE_COMPONENT=Node Component
BUSIORDER.FUNCTION_NAME=Function Name
BUSIORDER.FUNCTION_TYPE=Function Type
BUSIORDER.URL=Function URL
BUSIORDER.DISPATCH_ORDER_TYPE=Dispatch Order Type
BUSIORDER.APPLY_TYPE=Apply Type
BUSIORDER.IS_DEFAULT=Is Default

BUSIORDER.SHOW_NAME=Show Name
BUSIORDER.SHOW_ORDER=Show Order
BUSIORDER.IS_TRRIGER_AUTO_NODE=Trigger Automatic Node

BUSIORDER.MANUAL_NODE_FUNC=Manual Node Function
BUSIORDER.AUTO_NODE_FUNC=Automatic Node Function
BUSIORDER.FUNCTION_TYPE_NAME=Function Type Name
BUSIORDER.PLE_SEL_FUNC_NODE=Please select Node Function.
BUSIORDER.MANUAL_FUNCTION_CFG =Manual Function Configure
BUSIORDER.TOOLTIP_ADD_ALL = Add All
BUSIORDER.TOOLTIP_DEL_ALL = Delete All
BUSIORDER.TOOLTIP_ADD_ONE = Add One Item
BUSIORDER.TOOLTIP_DEL_ONE = Delete One Item
BUSIORDER.TOOLTIP_MOVE_UP= Move up
BUSIORDER.TOOLTIP_MOVE_DOWN= Move down
BUSIORDER.WORK_ORDER=Work Order
BUSIORDER.DISPATCH_ORDER=Dispatch order
BUSIORDER.SEARCH_NODE=search node name
BUSIORDER.TOOLTIP_AUTO_FUNCTION_DEFAULT=default value's format:key1=value|key2=value|key3=value
#########################################################################################
BUSIORDER.NODE_AUTO_FUCTION_ID=Node Automatic Function ID
BUSIORDER.NODE_AUTO_FUCTION=Node Automatic Function
BUSIORDER.SEQ=Sequence
BUSIORDER.NODE_MANUAL_FUCTION_ID=Node Manual Function ID
BUSIORDER.DEFAULT_VALUE=Default Value
BUSIORDER.PLS_SEL_NODE_AUTO_FUNC=Please select the node automatic function.
BUSIORDER.DISPATCH_TYPE_NAME=Dispatch Type Name
#################################
BUSIORDER.DISPATCH_RULE=Dispatch Rule
BUSIORDER.RULE_DEFINE=Rule Definition
BUSIORDER.ADD_RULE_DEFINE=Please add rule definition.
BUSIORDER.ORDER_TYPE=Order Type
BUSIORDER.MANUAL_EXE_TYPE=Manual
BUSIORDER.AUTO_EXE_TYPE=Automatic
BUSIORDER.RULE.TIME_UNIT = Time Unit
BUSIORDER.RULE.WARN_LIMIT = Warn Limit
BUSIORDER.RULE.FINISH_LIMIT = Finish Limit
BUSIORDER.RULE.ONLY_WORK_DAY = Only Working Day
BUSIORDER.RULE.WORK_DAY_LIMIT = Only Working Day
BUSIORDER.RULE.WARN_RULE = Warn Rule
BUSIORDER.RULE.SLA_LIMIT = Flow Limit
BUSIORDER.RULE.TIME_RULE = Time Limit
BUSIORDER.WEEK=Week
BUSIORDER.DAY=Day
BUSIORDER.HOUR = Hour
BUSIORDER.MINUE=Minute
BUSIORDER.RULE.REF_TIME_TYPE=Refer Limit Type
BUSIORDER.RULE.THREH_TYPE = Value Type
BUSIORDER.RULE.THREH_VALUE=Value
BUSIORDER.RULE.THREH_UNIT=Value Unit
BUSIORDER.RULE.NOTIFY_TYPE=Advice Type
BUSIORDER.RULE.WARN_OBJECT_TYPE = Warn Object Type
BUSIORDER.RULE.WARN_OBJECT_LIST = Warn Object List
BUSIORDER.RULE.PROCESS_LIMIT=Flow Limit
BUSIORDER.RULE.WARN_OBJECT_NUMBER = Warn Object Number
BUSIORDER.RULE.PRE_WARN_LIMIT=Warn Limit
BUSIORDER.RULE.PRECENTAGE= Percent
BUSIORDER.RULE.ABSOLUTE = Absolute
BUSIORDER.RULE.ORDER_DEALER = Task Dealer
BUSIORDER.RULE.ASSIGN_DEALER = Executor
BUSIORDER.RULE.ORDER_AUTHOR = Creator
BUSIORDER.RULE.HAD_RULE_TPL = Please choose another rule template, the template has been generated instance.
BUSIORDER.SAVE_SUCCESS = Succeed in saving the time limit.
BUSIORDER.DELETE_SUCCESS = Succeed in deleting the template instance. 
BUSIORDER.CONFIRM_DELETE = Are you sure to delete?
BUSIORDER.SAVE_RULE_DISP_SUCCESS = Succeed in saving the rule definition. 
BUSIORDER.SAVE_RULE_DISP_ADD_SUCCESS = Succeed in adding the rule definition. 
BUSIORDER.SAVE_RULE_DISP_EDIT_SUCCESS = Succeed in modifying the rule definition. 
BUSIORDER.SAVE_RULE_DISP_DELE_SUCCESS = Succeed in deleting the rule definition. 
BUSIORDER.DELETE_WARN_RULE_SUCCESS = Succeed in deleting the warn rule. 
BUSIORDER.ADD_WARN_RULE_SUCCESS = Succeed in adding the warn rule. 
BUSIORDER.MOD_WARN_RULE_SUCCESS = Succeed in modifying the warn rule. 

##########################validate########
BUSIORDER.TIME_UNIT_VAL = Please choose time unit. 
BUSIORDER.MUST_NUMBER_VAL = Please input the number. 
BUSIORDER.MUST_INPUT_ITEM = Please select the work order type.
BUSIORDER.INPUT_REFER_LIMIT = Please choose the Refer Limit Type.
BUSIORDER.INPUT_THREH_TYPE  = Please choose the value type.
BUSIORDER.INPUT_ADVICE_TYPE = Please choose the advice type.
BUSIORDER.THREH_UNIT = Please choose the value unit.
BUSIORDER.INPUT_THREH_VALUE = Please input the value.
BUSIORDER.INPUT_WARN_OBJECT_TYPE = Please choose the warn object type.
BUSIORDER.INPUT_WARN_LIMIT = Please input the warn limit.
BUSIORDER.INPUT_FINISH_LIMIT = Please input the finish limit.
BUSIORDER.ATTENTION =Note: Please define a rule, and then define the process time limit.
BUSIORDER.INPUT_ORDER_TYPE = Please choose the order type.
BUSIORDER.INPUT_OPER_MAN = Please choose the Operator.
BUSIORDER.SELECT_SCRIPT = Please choose the rule script expression.
BUSIORDER.SELECT_STAFF_ORG = Please choose the staff or organization.
BUSIORDER.SELECT_USER_GROUP = Please choose the user group.
BUSIORDER.TEMPLATE_TITLE=Flow Type
BUSIORDER.TYPE_SELECT_TITLE=Select Type
BUSIORDER.PROCESS_TITLE=Select Flow
BUSIORDER.PROCESS_NO=Flow No
BUSIORDER.PROCESS_NAME=Flow Name
BUSIORDER.DELETE_PROCESS_SUCCESS=Succeed in deleting the flow.
BUSIORDER.ADD_PROCESS_SUCCESS=Succeed in adding the flow.
BUSIORDER.DELETE_PROCESS_FAIL=Fail to delete the flow.
BUSIORDER.ADD_PROCESS_FAIL=Fail to add the flow.
BUSIORDER.MOD_PROCESS_FAIL=Fail to modify the flow.
BUSIORDER.MOD_PROCESS_SUCCESS=Succeed in modifying the flow.
BUSIORDER.PLS_SEL_PROCESS=Please choose the flow
BUSIORDER.PLS_SEL_DISPATCH_ORDER_TYPE=Please choose dispatch order type.
BUSIORDER.WORKORDER_DETAIL=Work Order Detail
BUSIORDER.WORKORDER_INFO=Work Order Information
BUSIORDER.FLOWINST=Flow Instance
####WorkOrderFlow.swf
BUSIORDER.ORDER_INFO=Order Information
BUSIORDER.IS_AUTOMATIC=Is Automatic
BUSIORDER.PARTY_NAME=Party Name
BUSIORDER.RELA_WORK_ORDER=Related Work Order
BUSIORDER.OPERATION_NAME=Operation Name
BUSIORDER.OPERATION_TIME=Operation Time
BUSIORDER.ATTRIBUTE_INFO=Feature Information
BUSIORDER.WF_ORG_NAME=Organization Name
BUSIORDER.ATTRIBUTE_ID = Attribute ID
BUSIORDER.ATTRIBUTE_NAME = Attribute Name
BUSIORDER.ATTRIBUTE_VALUE = Attribute Value

#WfTemplateCatg.swf
BUSIORDER.WF_TEMPLATE_CATG_TITLE=Work Flow Template
BUSIORDER.WF_TEMPLATETITLE=Work Flow Template Management
BUSIORDER.WF_TEMPLATE_CATG=Work Flow Template
BUSIORDER.TEMPLATE_CATG_NAME=Name
BUSIORDER.CHILDREN_IS_NOT_NULL=Fail to delete the selected item, because it has child items

#NodeAttrWin.swf
BUSIORDER.ATTR_ID=Feature
BUSIORDER.IS_RETURN_BPM=Is Return BPM
BUSIORDER.ATTR_PATH=Feature Patch
BUSIORDER.DISP_ORDER=Display Order
BUSIORDER.ATTR_TITLE=Select Feature
BUSIORDER.IS_RETURN_BPM_Y=Yes
BUSIORDER.IS_RETURN_BPM_N=No
BUSIORDER.ADD_ATTR= Add Node Feature

BUSIORDER.SEARCH_NODE_NAME=Add Node Feature
BUSIORDER.COMPLETE=Complete

BUSIORDER.NO_EXCEPTION=No exception found

BUSIORDER.PROVISIONING_DETAIL=Provisioning Detail 
BUSIORDER.DELIVERY_ORDER_LIST=Delivery Order List 
BUSIORDER.DISP_NOTIFY=Dispatch Notify
BUSIORDER.EMAIL=Email
BUSIORDER.NOTIFY_TYPE=Notify Type
BUSIORDER.ADVICE_CHANNEL=Advice Channel
BUSIORDER.OBJECT_NAME=Object Name
BUSIORDER.NOTIFY_OBJECT=Notify Object
BUSIORDER.NUMBER=Number
BUSIORDER.NOTIFY_A=Notify to dispatch staff
BUSIORDER.NOTIFY_B=Notify to dispatch organization leader
BUSIORDER.NOTIFY_C=Notify to dispatch group leader
BUSIORDER.NOTIFY_D=Notify to fixed object
BUSIORDER.NOTIFY_E=Notify to component Object
BUSIORDER.EMAIL_CC_LIST=CC

BUSIORDER.END_TIME=End Time
BUSIORDER.START_TIME=Start Time
BUSIORDER.START_NODE=Start Node
BUSIORDER.END_NODE=End Node
BUSIORDER.OPER_MAN_TYPE=Operator Type
WORK_ORDER_STATE=State
