#Created by JInto - www.guh-software.de
#Thu Mar 15 10:37:02 CST 2012
P_ACCOUNT_FORBIDDEN=The account is forbidden.
P_ACCOUNT_IS_FREEZE=The account is freeze.
P_ACCOUNT_NOTEFFECTIVE=The account is not effective.
P_ALARM=Alarm
P_CANCLE=Cancel
P_CAPSLOCK_IS_ON=CapsLock is on.
P_COPYRIGHT=Copyright 2010, ZTEsoft Technology Co.,LTD , www.ztesoft.com , All rights reserved.
P_DEFAULT_PORTAL=Default Portal
P_DEFAULT_PORTAL_NOT_EXIST=The default portal does not exist or is not available.
P_ERROR=Error
P_EXCEED_ONLINENUM=Exceeding the max online number of this user.
P_GO_BACK=Link to 
P_HINT_LOGIN_FAIL_TIMES=You have tried for {0} time(s),and the account will be locked after {1} failed logon attempt(s).
P_KEY_ECHO_PASSWORD=Confirm Password
P_KEY_HIGH=High
P_KEY_HIGHER=Higher
P_KEY_LOW=Low
P_KEY_LOWER=Lower
P_KEY_MEDIUM=Medium
P_KEY_PASSWORD=Password
P_KEY_OLD_PASSWORD=Old Password
P_KEY_SESSION_TIMEOUT=Your session has timed out, or you haven't logged on. Please login again.
P_KEY_BEEN_KICKED=You have been kicked from logged on status.
P_KEY_ABNORMAL_ACCOUNT=Your account may have problems, please contact the IT administrator.
P_KEY_USER_NAME=User Name
P_LOGIN_NOSTAFF=The account does not exist.
P_LOGIN_PAGE=Login Page
P_LOGIN_PASSWORD_ERROR=The password is wrong.
P_ACCOUNT_OR_PASSWORD_ERROR=The account or password is wrong.
P_LOGIN_PWD=Password
P_LOGIN_USER=User ID
P_LOGIN_USER_EFFECT_ERROR=The user has not effected by now.
P_LOGIN_USER_STATE_X_ERROR=The user has already expired. 
P_MESSAGE=Message
P_MOD_PASSWORD_NOW=Do you want to modify it now?
P_MSG_EXCEED_RETRY_LIMIT=Your account is locked. 
P_MSG_UNLOCK_BY_ADMINISTRATOR=Please contact the Administrator.
P_MSG_UNLOCK_AUTOMATIC=Please try again after {0} minutes.
P_NO=No
P_NOT_ALLOW_ACCESS=You are not allowed to access this web page. Please contact the administrater.
P_OK=OK
P_PASSWORD_EXPIRED=The password is expired, please modify it.
P_PASSWORD_IS_DEFAULT=Need to modify the password for the first time.
P_PASSWORD_IS_DEFAULT1=The password is same with the default password.
P_PASSWORD_WILL_EXPIRED=The password will be expired after {0} days.
P_LOGIN_FAIL_CHANGE_SECURITY=Password does not match the user's security level rules, please change your password.
P_PROMOTE=Promote
P_OLD_PWD_IS_NULL=Password not null.
P_PWD_IS_NULL=Password not null.
P_PWD_LENGTH_ERROR=The length of Password is between {0} and {1}.
P_PWD_MIN_LENGTH_ERROR=The length of password is less than the minimum length {0}. Please input again.
P_OLD_PWD_MAX_LENGTH_ERROR=The length of old password is greater than the maximum length {0}. Please input again.
P_PWD_MAX_LENGTH_ERROR=The length of password is greater than the maximum length {0}. Please input again.
P_PWD_MAX_LENGTH=Password max length is {0}.
P_PWD_MIN_LENGTH=Password min length is {0}.
P_PWD_NOT_SAME=The password entry does not match. Please try again.
P_PWD_NULL=Please input the user password.
P_SECURITY_LEVEL=Security Level
P_SYS_LOGIN=System Login
P_SYS_NAME=ZSmart
P_SYS_WELCOME_MSG=ZSmart
P_USER_EXPIRED=The account is expired
P_USER_NAME_LENGTH_ERROR=The length of User ID is between {0} and {1}.
P_USER_NAME_NULL=Please input the User ID.
P_USER_NAME_MAX_LENGTH_ERROR=The length of User ID is greater than the maximum length {0}. Please input again.
P_PWD_COMPOTION_2=The new password must contains letters and numbers.
P_PWD_COMPOTION_3=The new password must contains letters and capital letters.
P_PWD_COMPOTION_4=The new password must contains letters, numbers and capital letters.
P_PWD_COMPOTION_5=The new password must contains letters, numbers, capital letters and special characters.
P_MODE_PWD_SUCCESS=Succeed in modifying the password.
P_VERIFICATION_CODE_IS_NULL=Please input the Code.
P_VERIFICATION_CODE_LENGTH_ERROR=The length of code should equals {0}. Please input again.
P_VERIFICATION_CODE_WRONG=The Code error, please enter again.
P_IP_NOT_ALLOWED_LOGIN=The client IP is not allowed to login.
P_LOGIN_FAIL_OTHER_REASON=Login failed because of other reasons, please contact system administrator.
P_LOGIN_CODE=Code
P_LANG_CHOOSE=Language
P_LOGIN_MOBILE=Mobile
P_LOGIN_MOBILE_GET=Get
P_LOGIN_CODE_SEND=Send
P_LOGIN_CODE_RESEND=Re Send
P_LOGIN_MOBILE_GET_ERROR=Get number failed.
P_LOGIN_MOBILE_GET_NULL=Phone number is empty, please manually enter or reobtain.
P_LOGIN_CODE_SEND_TIMEOUT=Send verification code timeout.
P_LOGIN_CODE_SEND_ERROR=Send authentication code failed.
P_LOGIN_AGAIN=Please login again.

P_ABORT_KEY_ABOUT=About ZSmart
P_ABORT_KEY_PRODUCT_NAME=Product Name\:ZSmart
P_ABORT_KEY_THANKS=Thank you for using ZSmart product.
P_ABORT_KEY_INCLUDE_PRODUCTS=Include Products\:
P_ABORT_KEY_PRODUCT_INFO=ZSMART_BC_V8.0&#13ZSMART_FTF_V8.0&#13ZSMART_FBF_V8.0&#13ZSMART_SMC_V8.0
P_ABORT_KEY_VERSION_DETAIL=Welcome to ZSmart. Version\:{0}. Release Date\: {1}. Copyright(c) 1999-2008 ZTEsoft Technology Co.,LTD. All Rights Reserved. If you need any help or have any concern, please email to ztesoft800@zte.com.cn or dial our customer support hotline +86-25-52871161 Thank you for using ZTEsoft ZSmart. Warning\: this computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law.
P_ABORT_KEY_COPYRIGHT=Copyright 2011, ZTEsoft Technology Co.,LTD , All rights reserved.
# \u4eceglobal\u6587\u4ef6\u79fb\u690d
HINT_LOGIN_FAIL_TIMES=You have tried for {0} times.
P_LOGIN_FAIL_HAS_LOGIN=The account has been logined, is forced to login (kicked out of other users)
HINT_REDIRECT_TIME=s

#JSP\u62a5\u8868 webtechfrm/report/ReportPrint.jsp
REPORT_LIST=Report List
REPORT_DETAIL=Report Detail
#JSP\u56fd\u9645\u5316
I18N_PROPERTIES=Properties International
I18N_DATABASE=DataBase International
I18N_RESOURCE_CATALOG=Resource Catalog
SEARCH_KEY=Search Key
SEARCH_VALUE=Search Value
SEARCH=Search
NEED_TRANS = Untranslated
HAVE_TRANS = Translated
KEY_INITIAL_VALUE=Initial Value

#\u9009\u62e9job
P_JOB_CHOOSE=Select Job
P_JOB_CHOOSE_TIPS=Please select the job.
#\u5b89\u5168\u6027
P_SECURITY_EXCEPTION=Security exception.
P_PWD_HAS_SPECIAL=Only contains numbers,letters and @#$%!&*