EE_EmailTempEditor=Email Template Editor
EE_Title=Title
EE_AddAttachment=Attachment:
EE_AttentionMsg=Attention:
EE_UploadFileMsg=Before upload file please compressed it,The type of the file is as follows: .zip, .rar, .gz, .bz2, .7z, .jar, .war
EE_PictureTypeMsg=The type of picture to recommend the use of .png, .jpg, .gif. 
EE_FileMaxSize=The maximum size of the file is 10M
EE_SpamKeywordList=The list of spam keyword
EE_SaveTemp=Save Templet
EE_AdvertName=Advert Name:
EE_AdvertUrl=Advert Url:
EE_AdvertComment=Advert Comment:
EE_NeedMonitor=Need Monitor:
EE_NotSupportFileType=The file type does not support.
EE_IsUploading=Ths fiel is uploading...
EE_PARAMS=Parameters
EE_MACROS=Macro
EE_LANGUAGE=Language
EE_EXECLUDE_MAX_SIZE=The file size exceeds the limit. The max size is {0}. 
EE_NO_ALLOWNED_FILE_TYPE=The file type is not support. The support type is {0}.
EE_UPLOAD_FAIL=Fail to upload the file.
EE_EXECUTE_FILE_COUNT=Execute the max file count of attachment.The max count is {0}.
EE_EMAIL_TITLE_IS_NULL=Please input the email title.
EE_EMAIL_DEFINITION_IS_NULL=Please input the advice definition\u3002
EE_EMAIL_LANGUAGE_IS_NULL=Please select the language.