JOURNAL.JL_ACCOUNT_NAME = Name
JOURNAL.JL_ACCOUNT_CODE = Journal Account Code
JOURNAL.JL_ACCOUNT = Journal Account
JOURNAL.COMMENTS = Comments
JOURNAL.REMARKS = Remarks

JOURNAL.JL_ACCT_PAIR_NAME = Journal Account Pair Name
JOURNAL.JL_ACCOUNT_PAIR = Journal Account Pair
JOURNAL.JL_ACCT_PAIR_DBNAME = Debit Account Name
JOURNAL.JL_ACCT_PAIR_CRNAME = Credit Account Name
JOURNAL.JL_ACCOUNT_PAIR_NOTEQU = Journal Account Pair DebitName can not equal Journal Account Pair CreditName
JOURNAL.JL_ACCOUNT_PAIR_DBANDCR = Journal Account Pair DebitName and Journal Account Pair CreditName has exist

JOURNAL.JL_CYCLE = Journal Cycle
JOURNAL.STATE = State
JOURNAL.OPEN = Open
JOURNAL.CLOSE = Close
JOURNAL.CYCLE_BEGIN_DATE = Cycle Begin Date
JOURNAL.CYCLE_END_DATE = Cycle End Date
JOURNAL.CLOSE_JLCYCLE = Close Journal Cycle

JOURNAL.JL_LOG = Journal Account Log
JOURNAL.SRCNAME = Source Table
JOURNAL.START_TIME = Start Time
JOURNAL.END_TIME = End Time
JOURNAL.DATA_QUANTITY = Data Quantity
JOURNAL.TOTAL_AMOUNT = Total Amount
JOURNAL.JL_DAY = Journal Day
JOURNAL.STATE_DATE = State Date
JOURNAL.CREATED = Created
JOURNAL.ROLLBACKED = Roll Backed
JOURNAL.FAILED = Failed

JOURNAL.TYPE = Data Query Type
JOURNAL.BY_DAY = By Day
JOURNAL.BY_CYCLE = By Cycle
JOURNAL.JL_TRANSTYPE = Translate Type
JOURNAL.JDAYORJCYCLE =  By Day or By Cycle
JOURNAL.AMOUNT = Amount

JOURNAL.JOURNAL_RULE = Journal Rule
JOURNAL.JL_RULE_DETAIL_CON_DETAIL = Journal Rule Detail Condition
JOURNAL.JL_REF_COND_TYPE = Journal Reference Condition Type
JOURNAL.PARAM1_VALUE = Condition Type
JOURNAL.JL_RULE_DETAIL_CON_VALUE = Journal Rule Detail Condition Value
JOURNAL.VALUE = Value
JOURNAL.NAME = Name
JOURNAL.RULE_DETAIL = Rule Detail
JOURNAL.JL_RULE_DETAIL_NAME = Journal Rule Detail Name
JOURNAL.ADD_RULE_DETAIL_COND =  Add Journal Rule Detail Condition
JOURNAL.RULE_DETAIL_COND =  Journal Rule Detail Condition
JOURNAL.JL_RULE_LIST = Journal Rule List
JOURNAL.JL_RULE_NAME =   Journal Rule Name
JOURNAL.JL_TRANS_TYPE =  Transaction Type
JOURNAL.IS_DEFAULT =  Is default
JOURNAL.EFF_DATE =	   effect of Date
JOURNAL.EXT_DATE =      expiry date
JOURNAL.RULE = Journal Rule
JOURNAL.ADD_RULE = Add Journal Rule
JOURNAL.ADD_RULE_DETAIL = Add Journal Rule Detail
JOURNAL.YES = YES
JOURNAL.NO = NO
JOURNAL.RULE_DETAIL_CON_MB = Journal RULE DETAIL Condition Value
JOURNAL.JL_ACCOUNT_PAIR_ID_IS_NULL = Journal Account Pair Is NULL
JOURNAL.FIRST_ADD_RULE_DETAIL_CON = FISRT Add Journal RULE DETAIL Condition
JOURNAL.RULE_DETAIL_CON_MB_EXIST = Journal Rule Detail Condition Value Exist
JOURNAL.RULE_IS_DEFAULT = Default journal rule should be only one.
JOURNAL.RULE_IS_DEFAULT_NOT_CONFIG = Journal Rule IS Default Don't   Need To ADD RULE DETAIL

JOURNAL.CONFIRM_CLOSE=Confirm Close

JOURNAL.BILLED = Billed
JOURNAL.UNBILLED = UnBilled
JOURNAL.EARNED = Earned
JOURNAL.UNEARNED = UnEarned
JOURNAL.PREVIOUS_BILLED = Previous Billed
JOURNAL.UNPREVIOUS_BILLED = UnPrevious Billed
JOURNAL.DB = Debit
JOURNAL.CR = Credit
JOURNAL.TOTAL_BILLED_EARNED = Total Billed Earned
JOURNAL.TOTAL_UNBILLED_BUT_EARNED = Total UnBilled But Earned
JOURNAL.TOTAL_BILLED_BUT_UNEARNED = Total Billed But UnEarned
JOURNAL.JL_CYCLE_IS_NULL = Please select the Journal Cycle
JOURNAL.TOTAL = Total
JOURNAL.CODE = Code

JOURNAL.CHECK_DEFAULT_LOWEST = Default journal rule should be at the bottom.

JOURNAL.PROCESS_START_DATE = Process Start Date
JOURNAL.PROCESS_END_DATE = Process End Date
JOURNAL.PROCESS_START_TIME = Process Start Time
JOURNAL.PROCESS_END_TIME = Process End Time
