ETOPUP.ET_AGENT_INFO=ETopup Agent Information
ETOPUP.ET_AGENT_PWD_CHECK=ETopup Agent Password
ETOPUP.ET_AGENT_RECHARGE_BRAND=ETopup Agent Recharge Brand
ETOPUP.EVOUCHER=Evoucher
ETOPUP.NEW_ET_AGENT=New Root ETAgent
ETOPUP.NEW_SUB_ET_AGENT=New Sub ETAgent
ETOPUP.ET_AREA=ETopup Area
ETOPUP.ET_AGENT_TYPE=ETopup Agent Type
ETOPUP.RECHARGEABLE=Rechargeable
ETOPUP.TRANSFERABLE=Transferable
ETOPUP.NUMBER=Number
ETOPUP.ET_AGENT_NAME=ETopup Agent Name
ETOPUP.EVOUCHER_VALUE=Evoucher Value
ETOPUP.ET_AGENT_PIC_NAME=Pic Name
ETOPUP.ET_AGENT_PIC_BIRTH_DATE=Pic Birth Date
ETOPUP.ET_AGENT_PIC_CERT_NBR=Pic Cert Nbr
ETOPUP.ET_AGENT_ADDRESS=Address
ETOPUP.ET_AGENT_CONTACT_NBR=Contact Nbr
ETOPUP.STATE=State
ETOPUP.ACTIVE=Active
ETOPUP.PAUSE=Pause
ETOPUP.PAUSE_UP_REL=Pause Relationship
ETOPUP.ET_AUTH_AGENT=Authorized Agent
ETOPUP.SUB_AGENT=Sub Agent
ETOPUP.RETAILER=Retailer
ETOPUP.EVOUCHER_TRANSACTION=Evoucher Transaction
ETOPUP.TRANSACTION_DATE=Transaction Date
ETOPUP.TRANSACTION_ID=Transaction Id
ETOPUP.TRANSACTION_TYPE=Transaction Type
ETOPUP.TRANSACTION_MSISDN=MSISDN(From/To)
ETOPUP.VOUCHER_TYPE=Voucher Type
ETOPUP.AMOUNT_UNIT=Amount/Unit
ETOPUP.BALANCE=Balance
ETOPUP.CHANNEL=Channel
ETOPUP.START_DATE=Transaction Date From
ETOPUP.END_DATE=To
ETOPUP.EXPORT=Export
ETOPUP.QUERY=Query
ETOPUP.ET_AGENT=ETopup Agent
ETOPUP.ETOPUP_OPERATION = Etopup Operation
ETOPUP.CHECK_PASSWORD = Check Password
ETOPUP.YES = Yes
ETOPUP.NO = No
ETOPUP.AGENT_CHECK_PASSWORD = Agent Check Password
ETOPUP.ET_AGENT=ETopup Agent
ETOPUP.EVOUCHER_ADJUST=Evoucher Adjust
ETOPUP.EVOUCHER_ADJUST_VALUE=Adjust Value
ETOPUP.EVOUCHER_ADJUST_COUNT=Adjust Count
ETOPUP.EVOUCHER_ADJUST_ADD=Add
ETOPUP.EVOUCHER_ADJUST=Adjust
ETOPUP.EVOUCHER_TYPE=Evoucher Type
ETOPUP.EVOUCHER_INFORMAION=Evoucher Informaion
ETOPUP.EVOUCHER_CODE=Evoucher Code
ETOPUP.AGENT_EVOUCHER_VALUE=Agent Evoucher Value
ETOPUP.AGENT_EVOUCHER_UNIT=Unit
ETOPUP.EVOUCHER_CANCEL=Cancel
ETOPUP.HINT_ADJUST_SUCCESS=Adjust Success
ETOPUP.HINT_INPUT_ADJUST_VALUE=Please input adjust value.
ETOPUP.AGENT_RECHARGE_BRAND_DETAIL = Agent Recharge Brand Detail
ETOPUP.ETOPUP_BRAND = Brand
ETOPUP.HINT_PROD_NOT_HAVE_STDCODE = The prod have not stdcode,the name of prod is {0}.
ETOPUP.ETOPUP_AREA_CONFIG = ETopup Area Configuration
ETOPUP.ETOPUP_AREA_DEFINE_NAME =Area Define Name
ETOPUP.EFF_DATE=Effective Date
ETOPUP.EXP_DATE=Expire Date
ETOPUP.EVOUCHER_TYPE_F=Fixed Value
ETOPUP.EVOUCHER_TYPE_A=Any Value
ETOPUP.NUM_PREFIX=Number Prefix
ETOPUP.HINT_DEL_CHILD=Parent node has child node, please delete child node first.
ETOPUP.CHANGE_LOGIN_PASSWORD=Change Login Password
ETOPUP.PASSWORD=Password   
ETOPUP.CONFRM_PASSWORD=Confirm Password  
ETOPUP.CHANGE_PASSWORD=Change Password
ETOPUP.ET_AREA_STAFF_VIEW = Area View
ETOPUP.ET_STAFF_AREA_VIEW = Staff View
ETOPUP.ETOPUP_AREA_RELA_STAFF = Etopup Area/Staff
ETOPUP.ETOPUP_AREA = Etopup area
ETOPUP.ETOPUP_STAFF = Staff 
ETOPUP.ETOPUP_AREA_STAFF_RELA = Etopup area staff rala
ETOPUP.ET_AGENT_NUMBER = Etopup Agent Number
