S-ACT-13855=Flow packages are ordered duplicatly.

FIJI-S-ACT-13858=Deposit refund failed, please check whether deposit refunded or not exist.
FIJI-S-ACT-13246=The state of subssriber has been blocked and can not be recharged.
FIJI-S-ACT-13402=Current state of subscriber is not allowed to do recharge.
FIJI-S-ACT-00446=subscriber have not last billing cycle bill
FIJI-S-ACT-00112=Not sufficient balance.
FIJI-S-PRF-00112=password not incorrect
FIJI-S-ACT-00347=Fee could not be negative.
FIJI-S-ACT-13710=The post-paid can not recharge non-basic balance by default.
FIJI-S-ACT-13855=Flow packages are ordered duplicatly.
FIJI-S-ACT-13882=Fail to find the current billing cycle.
FIJI-S-ACT-00001=The date format error.
FIJI-S-ACT-00002=The startDate must be within three months.
FIJI-S-ACT-00003=Not all subscribers of the account have been terminated.
FIJI-S-ACT-13896=The subscriber must be active state.
FIJI-S-ACT-00004=The action is invalid.
FIJI-S-ACT-00005=The ceilLimit can not less than dailyCeilLimit.
FIJI-S-ACT-13415=The value of charge must greater than zero.
FIJI-S-ACT-00032=Fail to find the subscriber.
FIJI-S-ACT-13901=Please enter the start and end date at the same time.
FIJI-S-ACT-13421=End date is earlier than start date.
FIJI-S-ACT-00034= memberMdn is empty.
FIJI-S-ACT-00035=masterMdn is empty.
FIJI-S-ACT-00036=The date is holiday,please select again.
FIJI-S-ACT-00006=The state of subssriber has been one way blocked and can not be transfered to.
FIJI-S-ACT-00007=The state of subssriber has been two way blocked and can not be transfered to.
FIJI-S-ACT-00008=Transfer Amount should be an integer.
FIJI-S-ACT-00009=The transfer amount should be more than 0 and less than available balance.
FIJI-S-ACT-00010=EffDate can not be empty.
FIJI-S-ACT-00011=Mobile Number is Invalid.
FIJI-S-ACT-00012=This number has been disconnected.
FIJI-S-ACT-00013=This account must be postpaid.
FIJI-S-ACT-00014=No subscribers under the account.
FIJI-S-ACT-00015=Non specific users cannot query.
FIJI-S-ACT-00016=The start date can not be later than the end date.
FIJI-S-ACT-00017=The param 'acctId' and 'cust' is not matched.
FIJI-S-ACT-00018=The param 'subsId' and 'cust' is not matched.
FIJI-S-ACT-00019=BALTYPECODE and BALID can not both be empty.
FIJI-S-ACT-00020=ADJUSTAMOUNT and EFFDATE and EXPDATE cannot be empty at the same time.
FIJI-S-ACT-00023=The balance does not meet the loan conditions.
#1982957
FIJI-S-ACT-13895=Quota Transfer is only applicable for prepaid and individual postpaid.
FIJI-S-ACT-13897=Quota Transfer is disabled in current DPP. Please enable if continue to transfer quota.
FIJI-S-ACT-13899=Configure for the transfer acct res can not be found.
FIJI-S-ACT-13900=The charge exceeds the max change value of balance type.
FIJI-S-ACT-13903=The balance before transfering out exceeds the floor limit.
FIJI-S-ACT-00453=The transfer charge of transfer-out can not larger than transfer-out max charge in 30 days.
FIJI-S-ACT-00359=The charge of transfer-out can not be negative or zero.
FIJI-S-ACT-00021=The acct res mapping relation has existed.
FIJI-S-ACT-00022=The acct res type is not same.
#2013600
FIJI-S-ACT-00113=Only 5UP User Can Order.
FIJI-S-ACT-00114=Only Once Order within One Month.
#2230844
FIJI-S-ACT-00037=Please check config [{}] ,the value is incorrect.
#2358333
FIJI-S-ACT-00024=Fail to add the balance share, because the balance is lower than the floor limit.
#2358631
FIJI-S-ACT-00400=Fail to add bal share, because ownerMsisdn and sendMsisdn are different.
FIJI-S-ACT-00401=The input Params [ACCT_RES_CODE] is empty.
FIJI-S-ACT-00402=The input Params [AMOUNT] must be positive.
FIJI-S-ACT-00403=Fail to add bal share, because msisdn is PostPaid.
FIJI-S-ACT-00404=Fail to add bal share, because ownerMsisdn is PostPaid.
#2380610
FIJI-S-ACT-00025=Fail to add the balance share, because the balance type is not allowed to set balance share.
#2424428
FIJI-S-ACT-00330=Maximum amount of transfer at one time is VT{0}
FIJI-S-ACT-00331=Minimum amount of transfer at one time is VT{0}
#2790832
FIJI-S-ACT-00332=The parameter [{}] can not empty.
FIJI-S-ACT-00333=The voda recharge rela is empty.
FIJI-S-ACT-00334=Fail voda recharge,acct is not postpaid user.
FIJI-S-ACT-00335=Fail voda recharge,acct is not prepaid user.
#3007670
FIJI-S-ACT-00336=Fail to make final bill, the subscriber has not been terminated.
FIJI-S-ACT-00337=Fail to make fanal bill, the time when the subscriber is terminated is not in current billing cycle.
FIJI-S-ACT-00338=Fail to make advance bill, the subscriber has been terminated.
#3018376
FIJI-S-ACT-00339=The subscriber has already immediately invoiced twice in this billing cycle.
#3301419
TECL-S-ACT-00340=The transfer amount is not in the configuration item.
TECL-S-ACT-00341=The subscription plan type is incorrect.
#3301421
FIJI-S-ACT-00342=The bal category is not data.
#3305281
FIJI-S-ACT-00343=The subscriber is not allowed to adjust balance at its current state.