lockedState = Screen locked, invalid operation
exportError = export fail
sys_protocol_001 = The system protocol not exists
sys_protocol_002 = The system protocol needs to be invalidated first

PROD_USER_PHONE_000001 = The user or phone does not exist.
PROD_USER_PHONE_000002 = The phone number is incorrect.
PROD_USER_PHONE_000003 = The phone number can not be empty!
PROD_USER_EMAIL_000001 = The user or email does not exist.
PROD_USER_EMAIL_000002 = Please contact admin to reset your password!

NG_PORTAL_MENU_FILE_000000 = Export Menu
NG_PORTAL_MENU_FILE_000001 = First Level Directory/Menu
NG_PORTAL_MENU_FILE_000002 = Second Level Directory/Menu
NG_PORTAL_MENU_FILE_000003 = Third Level Directory/Menu
NG_PORTAL_MENU_FILE_000004 = Fourth Level Directory/Menu
NG_PORTAL_MENU_FILE_000005 = Code
NG_PORTAL_MENU_FILE_000006 = URL
NG_PORTAL_MENU_FILE_000007 = Type
NG_PORTAL_MENU_FILE_000008 = Parent Menu Code
NG_PORTAL_MENU_FILE_000009 = Icon
NG_PORTAL_MENU_FILE_000010 = Status
NG_PORTAL_MENU_FILE_000011 = MenuId
NG_PORTAL_MENU_FILE_000012 = system
NG_PORTAL_MENU_FILE_000013 = Sequence
NG_PORTAL_MENU_FILE_000014 = Level
NG_PORTAL_MENU_FILE_000015 = Open type
NG_PORTAL_MENU_FILE_000016 = Hash
NG_PORTAL_MENU_FILE_000017 = Description




USERNAME_EMPTY = User name cannot be empty!
PASSWORD_EMPTY = password cannot be empty!
EXCEPTION =  verification error
PASSWORD_ERROR = Password error!
USER_EMPTY = user does not exist
POT-ACCESS-NET-001 = Users can only login in through intranet, please contact administrator for public login!
POT-DRMRPC-001 = Access UC Service error, please contact administrator.
POT-DRM-VERIFICATIONCODE-WRONG = Your verificationCode is wrong!
POT-DRM-VERIFICATIONCODE-EXPIRED = Your verificationCode is expied!.
POT-LOGIN-00020 = User login for the first time, please change the password!
POT-LOGIN-00021=At present, users have logged in from the machine.
POT-USR-00100 = Fail to delete the role, because it has been referenced by job.
POT-MAGIC-00010 = Magic code is expired.
HOLIDAY_ERROR_001=System holidays already exist
HOLIDAY_ERROR_002=Please remove the bound work group first
HOLIDAY_ERROR_003=Please remove the corresponding holiday of this type first
S-MSGBT-005 = The same level name exists. Please input again.
S-MSGBT-007 = The same directory name exists. Please input again.
S-MSGBT-008 = Fail to delete,because it has children.
S-MSGBT-009 = Fail to delete.
S-MSGBT-010 = Fail to delete.
POT-DELEGATE-001 = Some delegate relationships already exist.
POT-DEALER-001=User binding IDN code does not match

POT-MENU-00001=The same menu name already exists. Menu name can use "center name (lowercase) - menu name"
POT-MENU-00002=The same privilege code already exists. Privilege code can use "center name (lowercase) - privilege  code"

POT-FILE-00010=The file path is rejected due to security reasons!
POT-ORG-00001=The Sub Type Code already exists.
POT-ORG-00002=The Sub Type Code can not be null.
POT-LICENSE-001=License have been exhausted .
S-EXPORT-001=excel column is empty.
S-EXPORT-002=internal server error.
S-EXPORT-003=export agents exceed.
S-EXPORT-004=File Not Found.
S-EXPORT-005=internal server error.
S-EXPORT-007=internal server error.
S-EXPORT-008=internal server error.
S-EXPORT-009=internal server error.
S-EXPORT-010=internal server error.
S-EXPORT-012=internal server error.
S-EXPORT-018=export data is empty.
