#Created by JInto - www.guh-software.de
#Mon Feb 27 15:32:06 CST 2012
P_MODE_PWD_SUCCESS=Succeed in modifying the password.
P_MOD_PWD_FAIL=Fail to modify the password.
P_PWD_USED_BEFORE=The password has been used.
