46430013=Your session has timed out.
46430014=Access is denied
46430015=Your accout has been logged in other places.
46430016=Access is denied
46430017=Request is too frequency
46430018=The account is forbidden.
46430019=The account is blocked.
46430020=The account is not effective.
46430021=Your account is locked.
46430022=The password is expired, please modify it.
46430023=The password will be expired after {0} days.
46430024=The password is same with the default password.
46430025=The account is expired.
46430026=The verification code error, please enter again.
46430027=Login failed because of other reasons, please contact system administrator.
46430028=Please login again.
46430029=You have been kicked from logged on status by the administrator. Please login again.
46430030=The account does not exist.
46430031=The account or password is wrong.
46430032=Username is empty.
46430033=Username'Length must shorter than 60.
46430034=Password is empty.
46430035=Password'length must shorter than 60.
46430036=Access Denied [{0}].
46430037=Encryption Error.
46430038=Malicious Token detected!
46430039=Malicious magic code detected!
46430040=Unable to login. You have exceeded the number of allowed concurrent sessions.
46430041=Password don't comply with safety rules
46430042=Secret key's length should be 16.
46430043=Magic code is expired.
46430044=Parsing failed.
46430045=The OTP Verification code is incorrect
46430046=The verification code has expired, please regain
46430047=Valid verification code error
46430048=Fail to send verification code.
46430049=Can't use send verification code function
46430050=Failed to send email.
46430051=Please click the following link to reset your password:
46430052=Access denied for your IP.
46430133=You need to unlock your account before you forget your password.
46430140=You do not have permission to create a new employee under the current organization.
46430141=Staff does not have permission to login!
43430142=The staff information is incomplete, you cannot use this function!
43430143=Exceeded the number of usable times, user will be locked. Please try again later.
43430144=Send failed,because the user neither have phone or email info!
46430145=The initial password has expired, we have sent you a new temporary password, please pay attention to check!
46420001=Screen locked, invalid operation
46420002=export fail
46420003=The system protocol not exists
46420004=The system protocol needs to be invalidated first
46420005=The user or phone does not exist.
46420006=The phone number is incorrect.
46420007=The user or email does not exist.
46420008=Please contact admin to reset your password!
46420020=User name cannot be empty!
46420021=password cannot be empty!
46420022=verification error
46420023=Password error!
46420024=User does not exist
46420025=Users can only login in through intranet, please contact administrator for public login!
46420026=User login for the first time, please change the password!
46420027=Fail to delete the role, because it has been referenced by job.
46420028=Magic code is expired.
46420029=System holidays already exist
46420030=Please remove the bound work group first
46420031=Please remove the corresponding holiday of this type first
46420032=The same level name exists. Please input again.
46420033=The same directory name exists. Please input again.
46420034=Fail to delete,because it has children.
46420035=Fail to delete.
46420036=Fail to delete.
46420037=Some delegate relationships already exist.
46420038=User binding IDN code does not match
46420039=The same menu name already exists. Menu name can use "center name (lowercase) - menu name"
46420040=The same privilege code already exists. Privilege code can use "center name (lowercase) - privilege  code"
46420041=The file path is rejected due to security reasons!
46420042=The Sub Type Code already exists.
46420043=The Sub Type Code can not be null.
46420044=Ad users are managed in LDAP and cannot use the forget password function.
46420045=Non EVC users log in with portal password cannot change password
46420046=EVC users but not log in with portal password cannot change password
46420047=The new password is invalid.
46420048=The component has been referenced by user, unable to modify the effect type.
46420049=The component has been referenced by role, unable to modify the effect type.
46420009=Bulletin type name already exists.
46420010=Bulletin type has children.
46420011=Bulletin type referenced.
46420012=Bulletin level name already exists.
46420013=Bulletin level referenced.
46420014=Bulletin template name already exists.
46420015=Fail to modify the password.
46420016=The same name already exists. Please input again.
46420017=MVNO user could not modify sysytem default layout.
46420018=You have no permission to modify the public layout.
46420019=The user code cannot be empty.
46430053=The user does not exist.
46430054=The role dose not exist.
46430055=Fail to delete the privilege, because it has been referenced by user privilege.
46430056=Fail to delete the privilege, because it has been referenced by role privilege.
46430057=Fail to delete the privilege, because it has been referenced by menu.
46430058=Fail to delete the privilege, because it has been referenced by component.
46430059=Fail to delete the directory, because it has submenu.
46430060=Fail to delete the directory, because it has subdirectory.
46430061=The same name already exists. Please input again.
46430062=Fail to modify the menu, because it can not be found.
46430063=Fail to delete the menu, because it has been referenced by directory.
46430064=Fail to delete the role, because it has been referenced by user.
46430065=Fail to modify the component, because it can not be found.
46430066=Fail to delete the portal, because it has been referenced by menu.
46430067=Fail to modify the portal, because it can not be found.
46430068=The same user code already exists. Please input again.
46430069=The user code is same as super's code. Please input again.
46430070=Fail to modify the user, because it can not be found.
46430071=The effective date can not be earlier than the current date. Please input again.
46430072=Fail to delete menu, because it has been referenced by component.
46430073=Fail to delete the role, because it has been referenced by privilege.
46430074=Fail to delete the directory, because it has been referenced by portal.
46430075=Fail to delete the type, because it has been referenced by portal.
46430076=Fail to delete the menu, because it has been referenced by portal.
46430077=The same role code already exists. Please input again.
46430078=Fail to modify or delete the role, because it has been locked.
46430079=The same role name already exists. Please input again.
46430080=The same menu name already exists. Please input again.
46430081=Fail to delete the menu, because it has been referenced by user.
46430082=Fail to delete the menu, because it has been referenced by role.
46430083=The same directory name already exists. Please input again.
46430084=Fail to delete the portal, because it has been referenced by user.
46430085=Fail to delete the portal, because it has been referenced by role.
46430086=The same portal is existed in the other apps,please input again.
46430087=Fail to delete the role, because it has been referenced by portal.
46430088=Fail to delete the component, because it has been referenced by user.
46430089=Fail to delete the component, because it has been referenced by role.
46430090=The same component name already exists. Please input again.
46430091=The same level code already exists. Please input again.
46430092=Fail to delete the portal, because it has been referenced by user.
46430093=Fail to delete the portal, because it has been referenced by role.
46430094=The component privilege of this object ID already exists in this menu.
46430095=The same privilege code already exists. Please input again.
46430096=Fail to modify the password, because the old password or user code is wrong.
46430097=Fail to modify the password, because the new password is same with the default password.
46430098=Fail to modify the password, because the length of new password is less than the minimum length {}.
46430099=Fail to modify the password, because the length of new password is grater then the maximum length {}.
46430100=Fail to modify the password, because the new password must contains letters and numbers.
46430101=Fail to modify the password, because the new password must contains letters, numbers and capital letters.
46430102=Fail to modify the password, because the new password must contains letters, numbers and special characters.
46430103=Fail to modify the password, because the new password must contains letters, numbers, capital letters and special characters.
46430104=Fail to modify the password, because the new password has been used before.
46430105=Parent node does not exist,please select again.
46430106=Fail to modify the help item, because it can not be found.
46430107=Fail to disable the portlet, because the portlet has been referenced by portal.
46430108=Fail to delete the help item,because it has subitem.
46430109=AD user cannot modify password.
46430110=Fail to modify the password, because the new password is weak password.
46430111=Mvno Administrator user does not modify menu.
46430112=The same email already exists. Please input again.
46430113=User effective date must not null.
46430114=The number of consecutive characters in the password exceeds {} times.
46430115=Usercode or password should not be null.
46430116=Fail to modify the password, because the new password does not comply with security rules.
46430117=The same phone already exists. Please input again.
46430118=You have changed password fail for three times, please try it again three minutes later.
46430119=Downloading file not exists.
46430120=The file is forbidden download.
46430121=The file exceeded the maximum upload size.
46430122=You can not download files in the current directory.
46430123=The current directory is forbidden uploaded file.
46430124=The type of file is forbidden uploaded.
46430125=The file is rejected due to security reasons!
46430126=The file path is rejected due to security reasons!
46430127=The same sp name already exists. Please input again.
46430128=The same std code already exists. Please input again.
46430129=Child is existed, can not be deleted.
46430130=You have no permissions to operate your own rights
46430131=MVNE's rights shouldn't be operated
46430132=Failed to operate MVNO Admin's Right since admin is not set yet.
46440000=Add Fail
46440001=Modify Fail
46440002=Delete Fail
46440003=Query Fail
46440004=Permission Denied
46400001=The IP address format is entered incorrectly. Please re-enter.
46400002=The port format is entered incorrectly. Please re-enter.
46400003=Please enter the correct domain format.
46400004=The AD is not exist.
46410001=The same area code already exists. Please input again.
46410002=Fail to delete the area, because it has been referenced by organization.
46410003=The same attribute code already  exists. Please input again.
46410004=The same attribute value code already exists in the value list. Please input again.
46410005=Value Code can not be repeated.
46410006=Fail to delete attribute, because it has been referenced.
46410007=Fail to delete the job, because it has been referenced by organization.
46410008=Fail to disable the job, because it has been referenced by organization.
46410009=Fail to delete the job, because it has been referenced by staff job.
46410010=Fail to disable the job, because it has been referenced by staff job.
46410011=The same organization code exists. Please input again.
46410012=Fail to delete organization, because it has been referenced by organization.
46410013=Fail to delete organization, because it has been referenced by organization attribute.
46410014=Fail to delete organization, because it has been referenced by staff.
46410015=The same staff code already exists. Please input again.
46410016=Please input the user code.
46410017=The same job name exists. Please input again.
46410018=Fail to delete the organization, because it has one or more sub-items.
46410019=Failed to delete the organization, because it has been referenced by staff.
46410020=Fail to quit the organization, because the staff only belong to this organization.
46410021=Fail to quit the organization, because the staff has jobs in this organization.
46410022=The email can not be empty.
46410023=The email already be used. Please input again.
46410024=The current property is dependent, can not be modified.
46410025=Fail to modify organization, because some jobs has been referenced by staff.
46410026=This area code {0} is invalid.
46410027=The same job code already exists. Please input again.
46410028=Cannot add this type of menu to your favorite list.
46410029=Your account is invalid.
46410030=The staff belongs to organization can not find leader.
46410031=The staff leave time cannot overlap.
46410032=operation failed: {0}.
46410033=You can only select one default layout.
46410034=Only three level menus are allowed to be created.
46410035=Page or query param can not be null.
46410036=Result size is too large.
46410037=The password must start with a letter.
46410038=The business area can only be bound to SSA.
46410039=This SSA has been bound to the business area.
46410040=The component code cannot be empty.
46410041=The component name cannot be empty.
46410042=The component privilege of this object ID cannot be empty.
46410043=The organization or job is not exist.
46410044=The dealer is frozen.
46410045=error msg is {0}.
46410048=The User Don't have available organization&job.
46410049=User''s mobile number is empty,please contact Administrator.
46410050=Cannot delete because there is associated data.
46410051=Please select where the announcement will be displayed!
46410052=There are employees in the group, which cannot be deleted.
46410053=The same group name exists, please modify.
46410054=The group name can not be empty.
46410055=Failed to save area information because the length of area name is required to be {0}, but it is actually {1}.
46410056=Fail to remove [{0}], because it has been referenced by [{1}].
46410057=The same [{0}] already exists. Please input again.
46410058=Fail to modify the password, because the user's password can only be changed by himself.
46410059=The user has exceeded the maximum number of failures to change the password. Please try again in {0} seconds.
46410060=Fail to modify the password, because the old password or user code is wrong, remaining attempts {0}
46410061=Auto unlock {0},lock time is up.
46410062=Auto lock {0},Because too many failed modify password attempts.
46410063= The start time is outside the allowed time range.The start time should after {0}.
46410064= The start and end time should be in the same month\u3002

4641001100=Del staff {0} from org {1} by {2}.
4641001101=granted role {0} to user {1}.
4641001102=Add staff {0} to orgs {1} by {2}.
4641001103=Add staff {0} by {1}.
4641001104=Remove staff {0} by {1}.
4641001105=Disable org {0} by {1}.
4641001106=Modify org {0} by {1}.
4641001107=Add org {0} by {1}.
4641001108=Modify staff {0} by {1}.
4641001109=export user info by {0}.
4641001110=Oauth2 login success,userId={0}.
4641001111=Oauth2 login success.
4641001112=Oauth2 login failed,userId={0},for {1}.
4641001113=Oauth2 login failed,for {0}.
4641001114=Disable staff {0} by {1}.
4641001115=Modify jobCode {0} by {1}.
4641001116=Add jobCode {0} by {1}.
4641001117=Enable jobId {0} by {1}.
4641001118=Disable jobId {0} by {1}.
4641001119=Delete the delegate relationship {0} by {1}.
4641001120=Modify the delegate relationship {0} by {1}.
4641001121=Add delegate relationships by {0}.
4641001122={0} is forced by {1}.
4641001123=removed menu name {0}.
4641001124=removed menu {0} from directory {1}.
4641001125=removed directory name {0}.
4641001126=Invalid userCode or password.
4641001127=Login Failed, please change your initial password.
4641001128=Login success.msgId is: {0} channel is: {1}.
4641001129=create staff and user.
4641001130=modify staff and user.
4641001131=disable staff and user.
4641001132=enable staff and user.
4641001133=query staff list.
4641001134=verify legitimacy of staff.
4641001135=query org by type.
4641001136=bind staff to job.
4641001137=unbind staff from job.
4641001138=query job list with page and job.
4641001139=query staff list by jobId list with page.
4641001140=query job list by staff id.
4641001141=Modify the system parameter.
4641001142=Modify the system parameter.detail:[Mask={0},Param Name={1}->{2},Current Value={3}->{4},Remarks={5}->{6}].
4641001143=%s is required;
4641001144=%s is too long;
4641001145=%s is not matching format;
4641001146=%s repeated with line %s;
4641001147=%s already exists;
4641001148=The imported data is empty.
4641001149=The imported data format is inconsistent with the template.
4641001150=Import fail.
4641001151=The imported staff do not have the job mandatory feature;
4641001152=The job mandatory feature %s is empty;
4641001153=Fail to send request.
4641001154=User phone is empty.
4641001155=User email is empty.
4641001156=System param [{0}] is null.
4641001157=The client application registration information is empty[{0}].
4641001158=Authentication failed [{0}].
4641001159=Modify the leader of org {0} as {1} by {2}.