S-BT-001=This category can not be deleted,because it is referenced by sub-category.If you are sure to delete it,please delete sub-category first.
S-BT-002=Attachment file is written to the database failed.
S-MSG-001=This directory can not be deleted,because it is referenced by sub-directory.If you are sure to delete it,please delete sub-directory first.
S-MSG-002=This directory contains the message, can not be deleted.If you are sure to delete it,please delete message first.