S-MSGBT-001=The same bulletin template name exists. Please input again.
S-MSGBT-002=Fail to delete the bulletin type, because it has one or more sub-items.
S-MSGBT-003=Fail to delete the bulletin type, because it has been referenced by bulletin.
S-MSGBT-004=The same bulletin type name exists. Please input again.
S-MSGBT-005=The same bulletin level name exists. Please input again.
S-MSGBT-006=Fail to delete the bulletin level, because it has been referenced by bulletin.
S-MSGBT-007=The same directory name exists. Please input again.
S-MSGBT-008=Fail to delete the directory, because it has one or more sub-items.
S-MSGBT-009=Fail to delete the directory, because it has been referenced by message.
S-MSGBT-010=Fail to delete the message level, because it has been referenced by message.