S-DOC-000001 = Catalog has children, please check it.
S-DOC-000002 = There is no effective version.
S-DOC-000003 = Please select doc format or event first.
S-DOC-000004 = There is no matching document format.
S-DOC-000005 = Failed to load the document format.
S-DOC-000006 = Lack of necessary param:{}.
S-DOC-000007 = Event is not defined, please check it.
S-DOC-000008 = Failed to unbind data source:[{}], due to the attributes of data source has been used.
S-DOC-000009 = Failed to send webservice message.

S-CC-00012 = The configuration {} does not have a value.
S-CC-00013 = {}
S-CC-00014 = Failed to get request contract formart xml from dms.