S-BMC-00001=The same billing instance name exists. Please input again:{0}.
S-BMC-00002=call back bmc service failed:{0}
S-BMC-00003=The same name of workflow instance exists, Please input again:{0}.
S-BMC-00004=The same name of timer exists, Please input again:{0}.
S-BMC-00005=The same program category name exists. Please input again:{0}.
S-BMC-00006=The same program name exists. Please input again:{0}.
S-BMC-00007=The same program code exists. Please input again:{0}.
S-BMC-00008=The same parameter name exists. Please input again:{0}.
S-BMC-00009=The same KPI Audit Name exists. Please input again.
S-BMC-00010=Fail to test KPI script:{0}
S-BMC-00011=In the foreign key, please manually cleaned using the proxy data and then delete.
S-BMC-00012=Fail to add the dunning letter type, because the service name does not exist:{0}.
S-BMC-00013=Fail to modify the dunning letter type, because the service name does not exist:{0}.
S-BMC-00014=The same dunning letter type name exists. Please input again:{0}.

S-BMC-10000=Account Step Summary
S-BMC-10001=Account Result Summary
S-BMC-10002=Rent Statistics Summary
S-BMC-10003=Billing Workflow Process
S-BMC-10004=Process Name
S-BMC-10005=Node Type
S-BMC-10006=Program Name
S-BMC-10007=Start Time
S-BMC-10008=End Time
S-BMC-10009=Duration(min)
S-BMC-10010=Proxy Name
S-BMC-10011=Audit Type
S-BMC-10012=Audit Result
S-BMC-10013=KPI Name
S-BMC-10014=KPI Value
S-BMC-10015=Operation History
S-BMC-10016=Area Name
S-BMC-10017=Product
S-BMC-10018=Billing Cost Detail
S-BMC-10019=Total Fee
S-BMC-10020=Discount Off Fee
S-BMC-10021=Account Item Billing Fee
S-BMC-10022=Rent Fee
S-BMC-10023=Data Fee
S-BMC-10024=Usage Fee
S-BMC-10025=One-Time Fee
S-BMC-10026=Adjust Fee
S-BMC-10027=Installment Fee
S-BMC-10028=User Number
S-BMC-10029=ARUP
S-BMC-10030=SQL Audit
S-BMC-10031=Audit Theme
S-BMC-10032=Audit Check
S-BMC-10033=KPI Audit
S-BMC-10034=Success
S-BMC-10035=Failed
S-BMC-10036=Pass
S-BMC-10037=Reject
S-BMC-10038=Billing Workflow Summary