#CompareValidator
equalError=The {0} should be equal to the {1}. Please input again.
greaterEqualError=The {0} should be greater than or equal to the {1}. Please input again.
greaterError=The {0} should be greater than the {1}. Please input again.
lessEqualError=The {0} should be less than or equal to the {1}. Please input again.
lessError=The {0} should be less than the {1}. Please input again.
notEqualError=The {0} can not be equal to the {1}. Please input again.

#DateTimeValidator
dateLessEqualError=The {0} can not be later than the {1}. Please select again.
dateLessError=The {0} should be earlier than the {1}. Please select again.
dateGreaterEqualError=The {1} should be earlier than the {0}. Please select again.
dateGreaterError=The {1} can not be later than the {0}. Please select again.
dateInvalid=The date is invalid. Please input or select again.

#EnhancedNumberValidator
numberDefinition=number
integerDefinition=integer
zeroDefinition=zero
incorrectNumberError=The {0} should be {1}. Please input again.
incorrectNumberLessError=The {0} should be {1} less than or equal to {2}. Please input again.
incorrectNumberGreaterError=The {0} should be {1} greater than or equal to {2}. Please input again.
incorrectNumberBetweenError=The {0} should be {1} between {2} and {3}. Please input again.

#ValidatorBase
requiredFieldError=Please input the {0}.
requiredSelectError=Please select the {0}.

#EnhancedStringValidator
tooLongError=The length of {0} is greater than the maximum length of {2} character(s). Please input again.
tooShortError=The length of {0} is less than the minimum length of {1} character(s). Please input again.
notBetweenError=The length of {0} should be between {1} character(s) and {2} character(s). Please input again.

#IPValidator
invalidIPAddress=The IP address is invalid. Please input again.
invalidIPClassA=The IP address of class A should be between 1 and 126. Please input it again.
invalidIPClassB=The IP address of class B should be between 128 and 191. Please input it again.
invalidIPClassC=The IP address of class C should be between 192 and 223. Please input it again.

#CurrencyValidator
invalidCurrency=The {0} should be number with {1} decimal places and maximum length of {2} digits. Please input again.
invalidPositiveCurrency=The {0} should be number greater than zero with {1} decimal places and maximum length of {2} digits. Please input again.
invalidNotNegativeCurrency=The {0} should be number not less than zero with {1} decimal places and maximum length of {2} digits. Please input again.
invalidMaxCurrency=The {0} should be number with {1} decimal places and not exceed {3}. Please input again.
invalidMaxPositiveCurrency=The {0} should be number greater than zero with {1} decimal places and not exceed {3}. Please input again.
invalidMaxNotNegativeCurrency=The {0} should be number not less than zero with {1} decimal places and not exceed {3}. Please input again.

#PopEditValidator
notExistsError=The {0} does not exist. Please select it again.

#EnhancedEmailValidator
invalidEmail=The email address is invalid. Please input again.

#DateTimePicker
monthNames=January,February,March,April,May,June,July,August,September,October,November,December
weekNames=S,M,T,W,T,F,S
shortMonthNames="  Jan,  Feb,  Mar,  Apr,  May,  Jun,  Jul,  Aug,  Sep,  Oct,  Nov,  Dec";
#ComboBox
selectPrompt=Please Select

#Button
ok=OK
cancel=Cancel
clear=Clear
search=Search
delete=Delete
yes=Yes
no=No

#FileExplorer
fileExportFormatSelect=Select Export File Format
fileFormatCSV=CSV Document
fileFormatPDF=PDF Document
fileFormatHTML=HTML Document
fileFormatXLS=XLS Document

#PageBar
firstPage=First
previousPage=Priv
nextPage=Next
lastPage=Last
numPerPage=Per Page
totalCount=Total\: {0}
total=Total\:
go=Go
rows=Rows\:
page=Page\:

#Upload
selectFile=Select File
selectEmptyFile=The file is empty, please upload again.
fileName=File Name
fileSize=Size
progress=Progress
fileFormat=Format\:
note=Note\:
fileTemplate=Template\:
hintMaxFilesCount=The maximum files count is {0}.
hintMaxFilesSize=The file size limit is {0}.
hintFilesInvalid=Failed to upload

#PopUp
message=Message

#SuperTabNavigator
closeOtherTabs=Close Other Tabs
closeTab=Close Tab
scrollLeft=Scroll tab list backward
scrollRight=Scroll tab list forward
viewTabList=View tab list

#DoubleClickTip
doubleClickTips=Note\: Double click for detail.

#SmartForm
randLessEqualError=The minimal {0} should be less than or equal to maximal {0}. Please input again.

channelEventDisconnect=Network communication failed, please try again.

#EnhancedCamera
getCameraErr=Failed to get the camera
cameraDenied=Camera access denied

#DataGrid
copySelectedCell=Copy Selected Grid Cell
copySelectedRow=Copy Selected Row
copySelectedRows=Copy Selected Rows
copyAllRows=Copy All Rows
export=Export

#AttachmentBar
dataFromCamera=Camera
dataFromScanner=Scanner
unuploadTip=Wait until the upload is complete
uploadErrTip=Upload failed,upload again:

#EnhancedModuleLoader
module=Module
loadFailed=load failed!

