ORANGE_CC_00001=The operation is only for the postpaid subscribers.
ORANGE_CC_00002=The operation is only for the prepaid subscribers.
ORANGE_CC_00003=No subscription plans available.
ORANGE_CC_00004=The number of members exceeds the limit of VPN.
ORANGE_CC_00005=The administrators cannot exit CUG.
ORANGE_CC_00006=The subscriber {0} already exists in the CUG.
## ORANGE_CC_00004 instead of
##ORANGE_CC_00007=Exceeds the max number amounts.
ORANGE_CC_00008=The subscriber has no balance, because the balance amount is positive.
ORANGE_CC_00009=The expiry date should be later than effective date, please input again.
ORANGE_CC_00010=This certificate has been used by other customer.
ORANGE_CC_00011=The subscriber does not belong to the MVNO {0}.
ORANGE_CC_00012=The certificate and the customer are not in the same routing.
ORANGE_CC_00013=The subscriber {0} does not exist.
ORANGE_CC_00014=The subscriber {0} is not administrator of the GUG.
ORANGE_CC_00015=The default price plan {0} does not exist in the system.
ORANGE_CC_00016=The dependent product {0} does not exist in the system.
ORANGE_CC_00017=Fail to add member {0}, because he has already been administrator of the CUG.
ORANGE_CC_00018=The user's subscription plan doesn't have any depended product which its service type is OPT-IN.
ORANGE_CC_00019=Configuration error, The user's subscription plan can only config a depended product which its service type is OPT-IN.
ORANGE_CC_00020=This user has ordered the dependent product.
ORANGE_CC_00021=The user does not subscribe to the dependent product, the product does not allow for state-dependent operation.
ORANGE_CC_00022=Fail to deactive the dependent product, because it isn't active.
ORANGE_CC_00023=The subscriber's default price plan is not allowed to cancel.
ORANGE_CC_00024=The subscriber did not order the product.
ORANGE_CC_00025=Fail to active the dependent product, because it isn't deactive.
ORANGE_CC_00026=The incorrect email address.
ORANGE_CC_00027=Fail to find any MVNO in the system by SP_ID {0}.