#Manual Work Order
PROV.FIJI.MSISDN=MSISDN
PROV.FIJI.CITY=City
PROV.FIJI.ROLLBACK_FLAG=RollBack Flag
PROV.FIJI.ROLLBACK_REASON=RollBack Reason
PROV.FIJI.EVENT_TYPE_NAME=Event Type Name
PROV.FIJI.CUSTONER_NAME=Customer Name
PROV.FIJI.CUSTONER_CODE=Customer Code
PROV.FIJI.EVENT_NAME=Event Name
PROV.FIJI.ORDER_NUMBER=Order Number
PROV.FIJI.EXPORT=Export
PROV.FIJI.EXPORT_FILE=Manual_Export
PROV.FIJI.DEVICE_MODIFY=Device Modify
PROV.FIJI.CUSTONER_CONTACT=Customer Number
PROV.FIJI.DEVICE_MODIFIED_SUCCESSFUL=Device modified successfully.
PROV.FIJI.DEVICE_MODIFY_REMARKS=Input Param