#Created by sunjie - sun.jie10@zte.com.cn
#2012-03-28
MVNO.LINK_SSO_GROUP=Associated SSO user group
MVNO.PARTITION_MANAGEMENT=Partition Management
MVNO.SP_NAME=Partition Name
MVNO.SP_ID=SP ID
MVNO.LEGAL_REP=Legal Rep
MVNO.CONTACT_NAME=Contact Name
MVNO.CONTACT_INFO=Contact Information
MVNO.STATE=State
MVNO.STATE_DATE=State Date
MVNO.SUPER_MANAGER=Super Manager
MVNO.PARENT_SP_ID=Parent SP ID
MVNO.LOGO=Logo
MVNO.URL=URL
MVNO.COMPANY_REGISTRATION_NUMBER=Company Registration Number
MVNO.REGISTERED_ADDRESS=Registered Address
MVNO.SCALE=Scale
MVNO.INDUSTRY=Industry
MVNO.CORE_BUSSINESS=Core Business
MVNO.FIXED_ASSET_AMOUNT=Fixed Asset Amount
MVNO.DECISION_MAKERS=Decision Makers
MVNO.DECISION_MAKERS_CONTACT=Decision Makers Contact
MVNO.CONTRACT=Contract
MVNO.SETT_RULE=Sett Rule
MVNO.STD_CODE=STD Code
MVNO.COMMENTS=Remarks
MVNO.BUTTON_LOCK=Lock
MVNO.BUTTON_UNLOCK=Unlock
MVNO.RESET_SUPER_MANAGER_PASSWORD=Reset Password
MVNO.USER_MANAGEMENT=User Management
MVNO.PARTITION_DETAIL=Partition Detail
MVNO.NEW_ROOT=New Root
MVNO.NEW=New
MVNO.EDIT=Edit
MVNO.DELETE=Delete
MVNO.OK=OK
MVNO.CANCEL=Cancel
MVNO.HINT_DELETE_ALERT=Are you sure to delete?
MVNO.HINT_DEL_PARTITION_SUCCESS=Succeed in deleting the partition.
MVNO.HINT_MOD_PARTITION_SUCCESS=Succeed in modifying the partition.
MVNO.HINT_ADD_PARTITION_SUCCESS=Succeed in adding the partition.
MVNO.HINT_LOCK_PARTITION_SUCCESS=Succeed in locking the partition.
MVNO.HINT_UNLOCK_PARTITION_SUCCESS=Succeed in unlocking the partition.
MVNO.PART_STATE_NORMAL=Normal
MVNO.PART_STATE_LOCK=Lock
MVNO.PART_STATE_DELETE=Invalid
MVNO.USER_NAME=User Name
MVNO.USER_PASSWORD=Password
MVNO.QUERY=Query
MVNO.RESET=Reset
MVNO.PARTITION_USER_DETAIL=User Management Detail
MVNO.HINT_DEL_USER_SUCCESS=Succeed in deleting the user.
MVNO.HINT_MOD_USER_SUCCESS=Succeed in modifying the user.
MVNO.HINT_ADD_USER_SUCCESS=Succeed in adding the user.
MVNO.HINT_RESET_PASSWORD_SUCCESS=Succeed in resetting the password of super admin.
MVNO.COPY_OBJECT=Copy Object
MVNO.USER_EMAIL=User Email

MVNO.SURE_TO_LOCK_THE_PARTITION=Are you sure to lock the partition?
MVNO.SURE_TO_UNLOCK_THE_PARTITION=Are you sure to unlock the partition?
MVNO.RESET_PWD_CONFIRM=Are you sure to reset the password of Administrator?
