INVENTORY.PURCHASE_ORDER_NO=Purchase Order NO.
INVENTORY.CREATOR_NAME=Creator Name
INVENTORY.SIM_FILE_GENERATION=SIM File Generation
INVENTORY.INTERNATIONAL_CODE=International Code
INVENTORY.MOBILE_CODE=Mobile Code
INVENTORY.IMSI_RANGE=IMSI Range
INVENTORY.IMSI_PROFILE=IMSI Profile
INVENTORY.ART_WORK=Art Work
INVENTORY.IMSI_FREE=IMSI Free
INVENTORY.ICCID_FREE=ICCID Free
INVENTORY.COMMENT=Comment
INVENTORY.PO_NO=PO NO.
INVENTORY.START_FROM=Start From
INVENTORY.END_TO=End To
INVENTORY.SIM_PROFILE=SIM Profile
INVENTORY.IMSI_GENERATION=IMSI Generation
INVENTORY.IMSI_HEADER=IMSI Header
INVENTORY.IMSI_SELECTION=IMSI Selection
INVENTORY.CARD_PURCHASE_ORDER_RECEIPT=Card Purchase Order Recepit

INVENTORY.THE_CHECK_NUM_LARGE=Number of more than limited.
INVENTORY.THE_CHECK_NUM_ZERO=The input number is 0,not to create.
INVENTORY.ERROR_QUERY_FIJI_ICCID_POOL=Fail to  query Fiji ICCID Pool.
INVENTORY.ICCID_ALREDAY_CREATE=The current ICCID has been created, please to re-create.
INVENTORY.ICCID_CREATE_OK=The ICCID create success.
INVENTORY.ADD_IMSI_RANGE_SUCCESSFULLY=Add IMSI Range successfully.
INVENTORY.ERROR_ADD_IMSI_RANGE=Fail to add the IMSI Range.
INVENTORY.IMSI_RANGE_IS_SAME=The same IMSI Range exists. Please input again.
INVENTORY.HINT_TABLE_LOCKED=Another operation while generates IMIS is in progress.
INVENTORY.ERROR_EDIT_IMSI_RANGE=Fail to modify the IMSI Range.
INVENTORY.HINT_CONTENT_SUCCESS_MOD=It has been modified successfully.
INVENTORY.HINT_CONTENT_QRY_DEL=Are you sure to delete it?
INVENTORY.HINT_FIJI_IMSI_RANGE_IS_CITED=The FijiImsiRange Note is cited,so it can't be deleted.
INVENTORY.ERROR_DEL_IMSI_RANGE=Fail to delete the IMSI Range.
INVENTORY.IMSI_START_SEQ_IS_CHANGE=The IMSI start sequence has changed, you need to refresh the page to re-create.
INVENTORY.ADD_IMSI_SUCCESS=Succeed in create the IMSI.
INVENTORY.HINT_NO_FIJI_ICCID_FOR_USE=There is no ICCID Poll exist,please check the data.
INVENTORY.HINT_FIJI_SIM_CARD_ORDER_FILE_PATH=The sim card purchase order DAT file path is empty, please set the file path.
INVENTORY.HINT_NOT_ENOUGH_IMSI_OR_ICCID=There is not enough IMSI or ICCID for this sim card purchase order.
INVENTORY.HIT_SYSTEM_BUSY=The system is busy,please wait a few minutes and try again.
INVENTORY.CREATE_CARD_PURCHASE_ORDER_SUCCESS=Succeed in adding the card purchase order.
INVENTORY.ERROR_ADD_CARD_PURCHASE_ORDER=Fail to add card purchase order.
INVENTORY.REMAKE_FILE=Remake File
INVENTORY.REMAKE_DTA_FILE=Succeed in remake the DAT file.
INVENTORY.ERROR_FILE_UPLOAD_FAIL=File upload failure.
INVENTORY.HINT_FILE_NOT_FOUND=File not found.
INVENTORY.HIT_ERROR_VOD_FILE_FORMAT=The vod file content format is incorrect,plase check the file.
INVENTORY.HIT_NOT_EXIST_CARD_PURCHASE_ORDER=The Sim Card Purchase Order does not exist.
INVENTORY.ARE_YOU_SURE_RECEIPT_ORDER_4_FIJI=The sim card number in VOD file and DAT file is not same,are you sure recepit this order?
INVENTORY.HIT_START_IMSI_NOT_EQUALS_ORDER=The IMSI start value not equals the order value. 
INVENTORY.HIT_START_ICCID_NOT_EQUALS_ORDER=The ICCID start value not equals the order value. 
INVENTORY.HIT_NOT_SIM_CARD_PURCHASE_ORDER_CLOSED=The Sim Card Purchase Order already has been closed.
INVENTORY.HIT_NOT_EXIST_CORRECT_HEAD=The file does not have the correct head part.
INVENTORY.ERROR_RECEPIT_CARD_ORDER_4_FIJI=Fail to recepit sim card pruchase order.
INVENTORY.RECEPIT_ORDER=Recepit Order
INVENTORY.HINT_IMSI_SELECTION_FORMAT_ERROR=The IMSI Selection must be 2-digit AND the value must be between  00 and 99.

INVENTORY.NUM_RECYCLE=Number Recycle
INVENTORY.HINT_RECYCLE_SIM_CARD_SUCCESS=Succeed in recycling the SIM card(s).
INVENTORY.HINT_RECYCLE_SIM_CARD_CONFIRM=Are you sure to recycle the SIM card(s).

FIJICOMMON.USERNAME=User Name
FIJICOMMON.PASSWORD=Password
FIJICOMMON.PWD_TYPE=Password Type
FIJICOMMON.PWD_TYPE_NONE=No Password
FIJICOMMON.PWD_TYPE_TXT=PasswordText
FIJICOMMON.PWD_TYPE_DIGEST=PasswordDigest
FIJICOMMON.ACTION_IDS=Action Ids
FIJICOMMON.ADD_USER_ACTION_SUCCESS=Add User Action Success!
FIJICOMMON.MOD_USER_ACTION_SUCCESS=Modify User Action Success!

#1599010
COMMON.MCCM.REMAINDER = Mccm Remind Message
COMMON.MCCM.QUERY = Query
COMMON.MCCM.DETAIL = Deatil
COMMON.ADVICE.MONITOR = Advice Monitor
COMMON.MCCM.NOURL = Please set MccmRemainderUrl.
COMMON.NOSUBS =The subscriber does not exist.
COMMON.HINT_SEARCH_MATCH_NULL = No records were found.
COMMON.HINT_NOT_RECORD = NO Record!
COMMON.HINT_PLEASE_SELECT_ITEM_FIRST = Please Select Item First!
COMMON.HINT_MOD_SUCCESS = Modify Success
COMMON.HINT_MOD_FAILURE = Modify Failure
#1786370
FIJI.CUSTOMERCARE.MENU_NAME=Menu Name
FIJI.CUSTOMERCARE.POSTPRE=post-paid&pre-paid
FIJI.CUSTOMERCARE.POST=post-paid
FIJI.CUSTOMERCARE.PRE=pre-paid
FIJI.ATHENA_SELF_DEL_CHILD_FIRST=Please delete the child menu first.
