#\u5171\u7528
Ok=Ok
Cancel=Cancel
Close=Close

#\u9876\u90e8\u5de5\u5177\u6761
AboutRichEditorTitle=About RichEditor
AboutRichEditor=RichEditor 1.0.1 (2012-02-08)\nCopyright \u00a9 <a href='www.ztesoft.com.cn' target='_blank'>ZTESoft</a>\nAll rights reserved.
ShowHtml=Show Html
SelectAllTip=Select All
LeftAlign=Left Align
CenterAlign=Center Align
RightAlign=Right Align
Font=Text Font
TextSize=Text Size
TextColor=Text Color
BgColor=Background Color
Bold=Bold
Italic=Italic
UnderLine=Under Line
Copy=Copy
Cut=Cut
Paste=Paste
Clear=Clear
Find=Find
Image=Image
Link=Link
UnLink=Clear Link
Help=Help

#\u5d4c\u5165\u8d44\u6e90
EmbedResWinTitle=Embed Resource
EmbedResWran=Input an URL on the web or select a local resource.
EmbedResSize=Max width {0},max height {1};min width {2},min height {3}.
EmbedResType=<li>Resource Type: jpg, png, gif</li>
ImageFiles=ImageFiles
FileUploading=FileUploading...
FileUploadError=File upload error, please check the network.
SecurityError=Security Error, please check the network.
Input=Input:
Browse=Browse
Size=Size:
Width=width
Height=height

#\u67e5\u627e\u548c\u66ff\u6362
FindAndReplace=Find/Replace
Find=Find:
FindAll=Find All

#\u8d85\u7ea7\u94fe\u63a5
LinkTitle=Super Link
URL=URL:
Target=Target:
DelLink=Delete Link
NoteMsg=Note
SelTextNote=Please select some text.
SuperLinkWarn=The select text can not contains special characters.
OperationConfirm=This operation can not roll back, are you sure?