#FROM openjdk:17-oracle
FROM eclipse-temurin:21-jdk-jammy

USER root:root

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} /apps/svc-role-0.0.1-SNAPSHOT.jar

#COPY resources /apps/resources

WORKDIR /apps

ENTRYPOINT ["java","-jar","/apps/svc-role-0.0.1-SNAPSHOT.jar"]
