S-RES-20033=The system is busy, please try again later.
S-RES-20041=The ICCID pool get the max value.
S-RES-20042=The same IMSI or ICCID exists in SIM card or open card purchase.
S-RES-20043=Please check the uploaded file.
S-RES-20044=Duplicated ICCID records exist in the uploaded file. Please check it.
S-RES-20045=Duplicated MSISDN records exist in the uploaded file.Pplease check it.
S-VPN-00001=The short number has been exits.

FIJI-S-RES-00001=The number state is not terminated.