#Created by JInto - www.guh-software.de
#Sat Mar 21 16:18:00 CST 2009
S-PVS-00011 = Fail to reactive abnormal work order.
S-PVS-00023 = The work order has been checked in already.
S-PVS-00026 = The work order not be checked out.
S-PVS-00201 = The node state is not checked out. It can not be checked in.
S-PVS-00504 = The work flow template can not be deleted, because it has been used.
S-PVS-00525 = The work flow template application with the same NE exists. Please input again.
S-PVS-00526 = The same work flow template application exists. Please input again.
S-PVS-00611 = Provisioning Monitor
S-PVS-00612 = Current
S-PVS-00613 = Minimum
S-PVS-00614 = Maximum
S-PVS-00615 = Average
S-PVS-00616 = # Graph created at
S-PVS-00617 = dd/MM/yyyy HH:mm:ss
S-PVS-00618 = Blocking Dispatch Order(s)
S-PVS-00619 = Abnormal Dispatch Order(s)
S-PVS-00620 = Abnormal Node Instance(s)
S-PVS-00621 = Work Order(s) In Process
S-PVS-00622 = Blocking Work Order(s)
S-PVS-00623 = Abnormal Work Order(s)
S-PVS-00624 = Default
S-PVS-00625 = Default
S-PVS-00603 = Fail to get the depend product attribute.
S-PVS-00701=The same access exists. Please input again.
S-PVS-00702=Fail to query the table of SA_CONFIG_SECTIONS.
S-PVS-00703=Fail to query the information of check method from the table of SA_CONFIG_ITEMS.
S-PVS-00704=Fail to query the table of SA_PARAM.
S-PVS-00705=Fail to query the id of check method from the table of SA_CONFIG_ITEMS.
S-PVS-00706=Fail to delete the table of SA_CONFIG_SECTIONS AND SA_CONFIG_ITEMS.
S-PVS-00707=Fail to add the table of SA_CONFIG_SECTIONS.
S-PVS-00708=Fail to add the table of SA_CONFIG_ITEMS.
S-PVS-00709=Fail to update the table of SA_CONFIG_SECTIONS.
S-PVS-00710=Fail to update the table of SA_CONFIG_ITEMS.
S-PVS-00711=Fail to query the table of SA_CONFIG_SECTIONS.
S-PVS-00712=Fail to query the table of SA_CONFIG_ITEMS.
S-PVS-00714=Fail to add this flow, the name is using by others.
S-PVS-00715=Fail to update this flow, the name is using by others.
S-PVS-00716=Fail to update this access, the name is using by others.
S-PVS-00717=Fail to query the information, please check the state of SA and refresh this page again. 
S-PVS-00718=Fail to query the information of NE thread from calling the interface method.
S-PVS-00713=Fail to generate WO by this template.
S-PVS-00719=Fail to query the information of the WE monitor.
S-PVS-00720=Fail to connect to the mml server.
S-PVS-00721=Fail to query the information of check method and input parameters from the table of SA_CONFIG_ITEMS.
S-PVS-00724=The same service & event type mapping exists. Please input again.
S-PVS-00725=The Thread info is null, may be the Instance is not start normally.
S-PVS-00728=Fail to remote the service, maybe the sa is stopped or configratrion is not right.
S-PVS-00730=Fail to synchronized with the PGW network element.
S-PVS-00731=The remote ne PGW executed failed.
S-PVS-00732=The event type with same parameter exists. Please input again.
S-PVS-00733=No record to export.
S-PVS-10043=The work order is not all completed,can not rollback now, please try again later.
S-PVS-10044=Sorry, it's not allowed to cancel this subs order while the work flow engine is dispatching the same order, please try later.
S-PVS-10045=Fail to delete the event type, because it has been referenced by event type parameter.
S-PVS-10046=The ne type does not exist.
S-PVS-10047=The same event type exists. Please input again.
S-PVS-10048=Fail to delete the event type, because it has been referenced by service network element mapping.
S-PVS-10049=Fail to delete the network element, because it has been referenced by the workstation.
S-PVS-10050=Fail to delete the network element, because it has been referenced by workflow template applicable rule.
S-PVS-10051=Fail to delete the network element, because it has been referenced by work order.
S-PVS-10052=The same network element name exists. Please input again.
S-PVS-10053=The HLR can not be added because the same name exists.
S-PVS-10054=The network element can not be modified because it does not exist.
S-PVS-10055=Fail to delete the workstation, because the workstation has been referenced by work order.
S-PVS-10056=Fail to delete the work station.
S-PVS-10057=The same operation mapping exists. Please input again.
S-PVS-10058=The same linkage rule exists. Please input again.
S-PVS-10059=Fail to delete the event type, because it has been referenced by manual work station.
S-PVS-10060=Fail to delete the event type, because it has been referenced by event type mapping.
S-PVS-10061=Fail to delete the parameter, because it has been referenced by event type.
S-PVS-10062=Fail to delete the access, because it has been referenced by network element.
S-PVS-10063=Fail to delete the section, because it has been referenced by item.
S-PVS-10064=The same event type mapping exists. Please input again.
S-PVS-10065=Fail to delete the business component, because it has been referenced by template node.
S-PVS-10066=The event type already has reverse event type. Please input again.
S-PVS-10067=Fail to import, because the same linkage rules exists.
S-PVS-10068=The format of the file is error, Please input again.
S-PVS-10069=Fail to import.
S-PVS-10070=Fail to import, because the same operation mapping exists.
S-PVS-10071=Fail to import, because the same service event exists.
S-PVS-10072=Fail to import, because the event type already has reverse event type.
S-PVS-10073=Fail to import, because the same event type exists.
S-PVS-10074=Fail to import, because the event type does not exist.
S-PVS-10075=Fail to import, because the parameter does not exist.
S-PVS-10076=The file does not exist.
S-PVS-10077=Fail to read the file.
S-PVS-10078=Fail to import, because the same event parameter exists.
S-PVS-10079=The same section name exists. Please input again.
S-PVS-10080=The same item key exists. Please input again.
S-PVS-10081=Fail to import, because the parameter[{0}] exists.
S-PVS-10082=File record is empty.
S-PVS-10083=Fail to import, because the service type does not exists.
S-PVS-10084=Import document has extra field.
S-PVS-10085=Fail to import, because the subscription event does not exists.
S-PVS-10086=Fail to import, because the provisioning operation does not exists.
S-PVS-10087=Fail to import,[{0}]cannot be null.
S-PVS-10088=The same parameter code exists. Please input again.
S-PVS-10089=Fail to delete the workflow template, because it has been referenced by workflow template applicable rule.
S-PVS-10090=Fail to delete the parameter, because it has been referenced by others.
S-PVS-10091=The same workflow template name exists. Please input again.
S-PVS-10092=The same business component name exists. Please input again.
S-PVS-10093=Fail to delete the manual event type, because it has been referenced by workflow node.
S-PVS-10094=Fail to delete the network element, because it has been referenced by the adapter.
S-PVS-10095=Error occured while handle the HLR.
S-PVS-10096=The same adapter name exists. Please input again.
S-PVS-10097=The same network element mapping rule exist.
S-PVS-10098=Fail to delete the network element, because it has been referenced by network element mapping rules.
S-PVS-10099=Fail to add  the workstation, because the workstation with the same NE already exists.
S-PVS-10100=Fail to modify  the workstation, because the workstation with the same NE already exists.
S-PVS-10101=Fail to start the rmi server.
S-PVS-10102=The same work station name exists. Please input again.
S-PVS-10103=The same instance name exists. Please input again.
S-PVS-10104=The same event type exists. Please input again.
S-PVS-10105=Fail to delete event type for maunal order. 
S-PVS-10106=Fail to get max value.
S-PVS-10107=The same number segment rule exists. Please input again.
S-PVS-10108=Fail to call the remoting service. Please check the server.
S-PVS-10110=Fail to delete the event type, because it has been referenced by the event type parameter.
S-PVS-10111=Fail to delete the event type, because it has been referenced by the event type mapping.
S-PVS-10112=Fail to delete the event type, because it has been referenced by the service event type mapping.
S-PVS-10113=Fail to delete the event type, because it has been referenced by the work order.
S-PVS-10114=Fail to delete the event type, because it has been referenced by the work station.
S-PVS-10115=Fail to submit the simulation order. Please check the log for more details.
S-PVS-10116=The parameter with the same code exists. Please input again.
S-PVS-10117=The account is null, please check it.
S-PVS-10118=Fail to get the synchronized work order acess point URL.
S-PVS-13003=Fail to validate MDN or IMSI resouce when provisioning system in Test mode.

S-SAS-00001=Fail to start the work thread. 
S-SAS-00002=Fail to initialize the OMC module plugIn\:DictPlugIn.
S-SAS-00003=The file name is empty.
S-SAS-00004=Fail to write the information to the file.
S-SAS-00005=The socket destination address is empty. 
S-SAS-00006=Fail to connect the remote interface server.
S-SAS-00007=Fail to bind the local IP address.
S-SAS-00008=Failed to parse command template configuration.
S-SAS-10001=Fail to create the Access module plugIn\:DataAccessPlugin.
S-SAS-10002=Fail to initialize the Access module plugIn\:DataAccessPlugin.
S-SAS-10003=Fail to create the Access module plugIn\:DictClass.
S-SAS-10004=Fail to initialize the Access module plugIn\:DictClass.
S-SAS-10005=Fail to initialize the dataAcess point.
S-SAS-10006=The database access SQLs are empty.
S-SAS-10007=Fail to create TCP access module plugIn\:ProtocolClass.
S-SAS-10008=Fail to initialize TCP access module plugIn\:ProtocolClass.
S-SAS-10009=Fail to build the data packet.
S-SAS-10010=Fail to send the data packet to the client\:{0}.
S-SAS-10011=Fail to check out work order.
S-SAS-10012=Fail to start the dataAcess point.
S-SAS-20001=Fail to create the main control module plugIn\:FlowControlClass.
S-SAS-20002=Fail to initialize the main control module plugIn\:FlowControlClass.
S-SAS-30001=Fail to create the network element module plugIn\:CommunicationsClass.
S-SAS-30002=Fail to initialize the network element module plugIn\:CommunicationsClass.
S-SAS-30003=Fail to create the network element module plugIn\:ProtocolClass.
S-SAS-30004=Fail to initialize the network element module plugIn\:ProtocolClass.
S-SAS-30005=Fail to create the network element module plugIn\:DictionaryClass.
S-SAS-30006=Fail to initialize the network element module plugIn\:DictionaryClass.
S-SAS-30007=Fail to create the network element module plugIn\:FlowControlClass.
S-SAS-30008=Fail to initialize the network element module plugIn\:FlowControlClass.
S-SAS-30009=Fail to build the heart beat packet.
S-SAS-30010=Fail to build the data packet.
S-SAS-30011=Fail to load configuration and initialize the net element protocol.
S-SAS-30012=Fail to start the service activetion process, please check instance configuration. 
S-SAS-30013=Fail to refresh access module, because it's running now, please hung-up or stop it first.
S-SAS-30014=Fail to refresh NE module, because it's running now, please hung-up or stop it first.
S-SAS-30015=Fail to execute the jython script, please check it.

S-SPN-00001=Fail to get Main Product Service Operation.
S-SPN-00002=Fail to get Depend Product Service Operation.
S-SPN-00003=Fail to get Depend Order AttrCode + Operation Map.
S-SPN-00004=Fail to get InDepend Order AttrCode + Operation Map.
S-SPN-00005=Fail to convert SPN soap.
S-SPN-00006=The soap author name or password is error.
S-SPN-00007=The soap type is error.
S-SPN-00008=Fail to valid the soap message.
S-SPN-00009=The message filed ACTION_ID cannot be identified.
S-SPN-00010=Fail to delete orders by batchId.
 
S-SPN-00011=Fail to modify order effectiveDate, because the order is in processing.
S-SPN-00012=Fail to modify order effectiveDate, because new effectiveDate is  earlier than current date.

S-WFE-00001=Fail to create Transaction Management proxy class instance. 
S-WFE-00002=Fail to create Class instance\:{0}.
S-WFE-00003=Fail to invoke function [{0}] dynamically.
S-WFE-00004=Fail to load cache data, maybe the topic name [{0}] is not exist.
S-WFE-00005=Fail to query cache data, the data of the topic [{0}] is empty.
S-WFE-00006=Fail to set the DAO class, the class type is not match.
S-WFE-00007=The abstract OMWorkOrderManager components can not be instancable,please check the PlugIns.ComponentsFactory config.
S-WFE-00008=Fail to decode the message in IPC server.
S-WFE-00009=Fail to execute message in IPC server.
S-WFE-00010=The validator is not Instantiate, please check the config plugIns.ComponentsFactory.
S-WFE-00100=The orderId and nodeInstId should not both be null.
S-WFE-00101=Fail to execute the OM_BC.
S-WFE-00102=The order can not be dispatched when it's in roll back state.
S-WFE-00103=The omorder's state must be ready.
S-WFE-00104=Fail to get the first work flow template node.
S-WFE-00105=The state of the node instance is not anticipative.
S-WFE-00106=Fail to query the work flow node OM_BC.
S-WFE-00107=Fail to get the next work flow template nodes. 
S-WFE-00108=The nodeInstance's state is invalid.
S-WFE-00109=The format of the condition expression is invalid .
S-WFE-00110=The back fill parameter value should not be null.
S-WFE-00111=Fail to get the judgment node attributable value.
S-WFE-00112=The input parameter does not contain eventType.
S-WFE-00114=Fail to dispatch the order.
S-WFE-00115=Fail to call the remote process\:service active.
S-WFE-00116=Fail to get work flow template.
S-WFE-00117=Fail to submit the subs order to do dispatch.
S-WFE-00118=Fail to cancel the subs order.
S-WFE-00119=Fail to reDispath the subs order.
S-WFE-00120=Fail to get first node when cancel the subs order.
S-WFE-00121=Sorry, it's not allowed to cancel this subs order while the work flow engine is dispatching the same order, please try later.
S-WFE-00122=The work order is not all completed, can not rollback now, please try again later.
S-WFE-00123=The om order already been canceled, can not cancel again.
S-WFE-00124=The om order already complete, can not cancel.
S-WFE-00125=The om order have not insert into the database. Can not dispatch now.
S-WFE-00126=Fail to execute concurrent bc node.
S-WFE-00127=The om order record is empty\uff0ccan not be canceled.
S-WFE-00128=The om order is been canceling now\uff0ccan not be canceled again.
S-WFE-00129=Fail to query SA order by the parent order item ID.
S-WFE-00130=Fail to execute node component.
S-WFE-00200=Fail to prior dispatch the order.
S-WFE-00201=Fail to update provisioning inner order detail and cache.
S-WFE-00202=Fail to call service activition synchronously.
S-WFE-00203=Fail to roll back the order to the target node.
S-WFE-01001=Fail to get network entity id.
S-WFE-01002=No work station exists.
S-WFE-01003=Fail to get necessary parameter,name\=[{0}],method\=[{1}],isRollBack\=[{2}].
S-WFE-01004=Failed to roll back executed network element commands. 
S-WFE-01005=Execute the work order array failed, but roll backs successfully.
S-WFE-01006=Execute the work order array failed.
S-WFE-01007=Failed to start the workflow engine process, please check instance configuration. 
S-WFE-01008=Fail to cancel the subs order.
S-WFE-01009=Sorry,it's not allowed to redo this subs order, because the subs order is provisioning now.
S-WFE-01010=The order item does not be dispatched.