#1018807  xp
ACCOUNT.RG=RG
#1018007 ZL
ACCOUNT.ACCOUNT_ID=Account ID
ACCOUNT.EVENT_DATE=Event Date

ACCOUNT.IPK_NAME=IPK_NAME
ACCOUNT.REPAYMENT_AMOUNT=Pay Debit Amount
#1459374  xp
FIJI.QUERY_VOUCHER_CARD=Query Voucher Card
FIJI.VOUCHER_CARD_NUMBER=Card Number
FIJI.VOUCHER_CARD_PASSWORD=Card Password
FIJI.VOUCHER_CARD_INFO=Voucher Card Information
FIJI.FACE_VALUE=Face Value
FIJI.VOUCHER_CARD_VALIDDAYS=Valid Days
FIJI.STATE=Status
FIJI.VOUCHER_CARD_SUCCESS_OK=User succeeds in authentication or recharge.
FIJI.VOUCHER_CARD_DB_BUSY=DB in the BOSS or the SCP system is busy. Cannot be recharged.
FIJI.VOUCHER_CARD_SYSTEM_BUSY=The system is busy for the request.
FIJI.VOUCHER_CARD_MESSAGE_ERROR=Failures occur in the message codes. Failed to decode.
FIJI.VOUCHER_CARD_NO_VOUCHER=The voucher is not found.
FIJI.VOUCHER_CARD_NOT_SUPPORT=The service terminal does not support the version No. of the protocol.
FIJI.VOUCHER_CARD_PASSWORD_ERROR=The voucher password is incorrect. Cannot be recharged.
FIJI.VOUCHER_CARD_EXPIRE_DATE=The voucher has expired. Cannot be recharged.
FIJI.VOUCHER_CARD_USED_ERROR=The voucher has been used. Cannot be recharged.
FIJI.VOUCHER_CARD_VOUCHER_LOCKED=The voucher is locked.
FIJI.VOUCHER_CARD_USING_ERROR=The voucher is frozen and out of service.
FIJI.VOUCHER_CARD_IDLE_ERROR=The voucher is in the unused status and not allowed to be recharged.
FIJI.ACC_NBR_NULL_ERROR=AccNbr is null.
#1456172
FIJI.BAN_LEVEL=BAN Level
#1459205
ACCOUNT.BANK_NAME=Bank Name
ACCOUNT.CHECK_NUMBER=Check Number
ACCOUNT.PAYMENT_METHOD=Payment Method
ACCOUNT.CHECK_OWNER_NAME=Check Owner Name
ACCOUNT.CHECK_ISSUE_DATE=Check Issue Date
ACCOUNT.CHECK_EXP_DATE=Check Exp Date
ACCOUNT.RECHARGING_DETAILS=Top Up Details
ACCOUNT.RECORD_EXTRA_FEE=Record Extra Fee
ACCOUNT.RATE_PLAN_NAME=Rate Plan Name

COMMON.TERMINATED_SUBS=Terminated Subscriber
BILLING.SUBS_LIST=Subscribers List
BILLING.DOUBLE_CLICK_SUBS_TO_SELECT=Double click on the subscriber to select it.
FIJI.MSISDN=MSISDN
BILLING.IS_SUBS_BAL=Is Subs Bal
BILLING.REASON=Reason
BILLING.ET_AGENT_DN=ETopup Agent
BILLING.PRE_BALANCE1=Pre-Balance1
BILLING.AFTER_BALANCE1=After-Balance1
ACCOUNT.BALANCE_TYPE1=Balance Type1
BILLING.BALANCE_TYPE1=Balance Type1
ACCOUNT.ET_AGENT_DN=ETopup Agent

FIJI.ACCOUNT.REMARKS=Remarks
FIJI.ACCOUNT.PAYMENT_SOURCE=Payment Source
#1775429
FIJI.TRANSFER_BALANCE_TYPE_NOT_ALLOWED=The balance type of transfer is not allowed.
FIJI.TRANSFER_IN_MUST_BE_POSTPAID=The transfer in must be postpaid.
#1796754
FIJI.ACCOUNT.ALLOCATE_IN=Allocate In
FIJI.ACCOUNT.ALLOCATE_OUT=Allocate Out

FIJI.REASON_CODE =  Reason Code

#1833114
FIJI.ACCOUNT.MANUAL_DUNNING_RECORD=Manual Dunning Record and History

#1982957
BILLING.TRANSFER_ACCT_RES=Transfer Acct Res
BILLING.ACCT_RES_NAME=Source Balance Type Name
BILLING.ACCT_RES_ID=Source Balance Type ID
BILLING.ACCT_RES_NAME_IN=Destination Balance Type Name
BILLING.ACCT_RES_ID_IN=Destination Balance Type ID
BILLING.GLID_SELECT_IS_NULL=Please select the transfer acct res.