#Created by JInto - www.guh-software.de
#Tue Mar 03 20:30:26 CST 2009
S-EVR-00001=Fail to recharge by the evoucher dealer.
S-EVR-00002=The evoucher dealer doesn't exist.
S-EVR-00003=The account for evoucher dealer doesn't exist.
S-EVR-00004=End subscriber for recharge doesn't exist.
S-EVR-00005=Fail to recharge by evoucher dealer for himself.
S-EVR-00006=Fail to check recharge by evoucher dealer for himself.
S-EVR-00007=The evoucher dealer can't do recharge action.
S-EVR-00008=The operation is limited due to configable charge limitation.
S-EVR-00009=The state of evoucher dealer is invalid for recharge action.
S-EVR-00010=The recharge action isn't allowed due to the brand limitation.
S-EVR-00011=Fail to check the password of evoucher dealer is or not valid.
S-EVR-00012=The input password of evoucher dealer isn't correct.
S-EVR-00013=Fail to check the evoucher dealer has enough stock.
S-EVR-00014=Fail to check the operation need the valid password.
S-EVR-00015=Fail to query the information of evoucher dealer by number.
S-EVR-00016=Fail to query the parent evoucher dealer.
S-EVR-00017=Fail to query the brands can be recharged by evoucher dealer.
S-EVR-00018=The evoucher dealer has no enough stock.
S-EVR-00019=The evoucher dealer has no suitable stock.
S-EVR-00020=Fail to record the evoucher operation.
S-EVR-00021=The evoucher amount is less than zero.
S-EVR-00022=The evoucher amount is not equal to the input quantity for transfer.
S-EVR-00023=The state of evoucher dealer is invalid for transfer out.
S-EVR-00024=The parent dealer of transfer in dealer isn't transfer out dealer.
S-EVR-00025=The transfer in dealer has no parent dealer.
S-EVR-00026=Fail to check the new evoucher dealer and the parent dealer are in the same area.
S-EVR-00027=Fail to register evoucher dealer automatically by the transaction action.
S-EVR-00028=Fail to query the area.
S-EVR-00029=The prefix of transfer in number isn't matched with the area of transfer out dealer.
S-EVR-00030=The state of evoucher dealer is invalid for transfer in action.
S-EVR-00031=The length of new password is invalid.
S-EVR-00032=Fail to change the password of evoucher dealer. 
S-EVR-00033=BO.serviceName can't match the method.
S-EVR-00034=Can't recharge for the same number with the same amount.
S-EVR-00035=Fail to change the state of evoucher dealer.
S-EVR-00036=The sub evoucher dealer doesn't exist.
S-EVR-00037=The evoucher dealers have no relationship.
S-EVR-00038=The prefix has already exist in another area.
S-EVR-00039=More than one overlapping discount rule.
S-EVR-00040=The evoucher is referenced by dealer stock.
S-EVR-00041=The evoucher is referenced by transaction.
S-EVR-00042=The evoucher dealer has already set the password for this operation.
S-EVR-00043=Fail to notify when the stock of dealer is less than the threshold value.
S-EVR-00044=The transaction type has the same limit amount.
S-EVR-00045=Fail to query stock.
S-EVR-00046=Fail to query the last transaction record.
S-EVR-00047=Fail to query the last recharge transaction record.
S-EVR-00048=The transaction record doesn't exist.
S-EVR-00049=Fail to generate the advice record for recharge action.
S-EVR-00050=Fail to generate the advice record for transfer action.
S-EVR-00051=Fail to generate the advice record for the pin of sub dealer. 
S-EVR-00052=The same dealer name has existed.
S-EVR-00053=The area doesn't match the area of parent dealer.
S-EVR-00054=The stock can't be less than zero. 
S-EVR-00055=Fail to send pin to dealer due to the target isn't his sub dealer.
S-EVR-00056=The sub dealer doesn't exist.
S-EVR-00057=No record for the sn.
S-EVR-00058=Fail to query data.
S-EVR-00059=Exceed the expire date.
S-EVR-00060=The input password is empty.
S-EVR-00061=Fail to query the last transfer record.
S-EVR-00062=Miss param for evoucher quantity.
S-EVR-00063=Fail to transfer by the evoucher dealer.
S-EVR-00064=No enough stock for specific evoucher.
S-EVR-00065=The area is referenced by dealer.
S-EVR-00066=No sub dealer.
S-EVR-00067=Too long for dealer name.
S-EVR-00068=Illegal recharge amount.
S-EVR-00069=No infomation for the number.
S-EVR-00070=The dealer with the same prefix and number has existed.
S-EVR-00071=Subscriber isn't exist.
S-EVR-00072=Fail to check validation.
S-EVR-00073=The apply of dealer with the same prefix and number has existed.
S-EVR-00074=Fail to operate due to dealer is suspended by parent dealer.
S-EVR-00075=The dealer number isn't begin with the prefix of the area.
S-EVR-00076=Fail to recharge.
S-EVR-00077=The total amount for multiple stock isn't equal to input amount.
S-EVR-00078=Fail to transfer due to the type of transfer out dealer is invalid.
S-EVR-00079=The area is referenced by evoucher dealer.
S-EVR-00080=The sub dealer stock doesn't exist.
S-EVR-00081=Fail to query EtMMLCommandType.
S-EVR-00082=Fail to add EtMMLCommandLog record.
S-EVR-00083=The input password isn't correct.

S-EVR-00100=The dealer with the same prefix and number has existed.
S-EVR-00101=The password can't be empty.
S-EVR-00102=The stock of dealer will be less than zero after adjustment.
S-EVR-00103=The evoucher[{}] of dealer will be less than zero afther adjustment.
S-EVR-00104=The same recharge brand rule has existed.
S-EVR-00105=The dealer has sub dealer.
S-EVR-00106=No stock for this type.
S-EVR-00107=The same evoucher code has existed.

S-EVR-00108=Conflict of Effective and Expire date. 
S-EVR-00109=The area is referenced by dealer.
S-EVR-00110=The prefix of area is referenced by dealer.
S-EVR-00111=Only one cash stock can be created.
S-EVR-00112=Only M8 subscriber can be recharged by dealer.
S-EVR-00113=The prefix of new dealer isn't matched with the parent dealer.
S-EVR-00114=An area with the same name already exists.Please input again.
S-EVR-00115=Recharge is forbidden by agent attribute:[EXP_SUBS_TRANSFER]=[{0}].
S-EVR-00116=Nephew transfer is forbidden by agent attribute:[EXP_NEPHEW_TRANSFER]=[{0}].
S-EVR-00117=Delear is forbidden to transfer to retailer by agent attribute:[EXP_RETAILER_TRANSFER]=[{0}].
S-EVR-00118=Same level agent transfer is forbidden by agent attribute:[EXP_SIBLING_TRANSFER]=[{0}].
S-EVR-00119=The etopup staff has been used by other etopup agent.
S-EVR-00120=Configuration account.CVBS2CBSWebserviceAddress can not be null.
S-EVR-00121=Can not find the balance for the subscriber.

S_EVR_00122 = Failed to add EtAgent.
S-EVR-00123=The purchase evoucher request doesn't exist.
S-EVR-00124=SubAgentDn is not a sub-agent of AgentDn
## TODO \u4fee\u6539\u4ee3\u7801\u4e2d\u7684\u5f15\u7528\uff0c\u7136\u540e\u628a\u8fd9\u4e2a\u6ce8\u91ca\u5220\u9664\u6389
S-EVR-00125=SubAgentDn is not a sub-agent of AgentDn

S-EVR-00126=AgentId does not match the AgentDn
S-EVR-00127=More than one Agent was found by the AgentDn
S-EVR-00128=The SN already exists
S-EVR-00129=Not find account book for etopup
#1551300
S-EVR-00130=Fail to recharge by evoucher dealer, because the payment amount should exceed the minimum amount.
S-EVR-00131=Fail to recharge by evoucher dealer, because the payment amount exceeds ceiling limit.
S-EVR-00132=Fail to transfer between dealer, because the transfer amount should exceed the minimum amount.
S-EVR-00133=Fail to transfer between dealer, because the transfer amount exceeds ceiling limit.
S-EVR-00134=Recall amount must greater than 0.
S-EVR-00135=Exceed the time to recall
S-EVR-00136=The Recharge Record to Recall not exist
S-EVR-00137=The recharge record doesn't exist.
S-EVR-00138 = Fail to recharge by evoucher dealer, because over the daily maximum recharge amount limit.
S-EVR-00139 = Fail to transfer between dealer, because over the daily maximum transfer amount limit.
S-EVR-00140 = The amount to reverse does not match the amount of recharge record
S-EVR-00141 = The record of Recharge has reversed
S-EVR-00142 = The sub dealer doesn't exist.
S-EVR-00143 = Can not transfer to self
S-EVR-00144 = Failed to reverse transfer, because the total reverse transfer amount exceeds the original transfer out amount
S-EVR-00145 = Transfer out dealer is busy
S-EVR-00146 = Transfer in dealer is busy
S-EVR-00147 = The purchase evoucher record state is not unconfirm.
S-EVR-00148 = Start time and end time can not be null;
S-EVR-00149 = Only one month transaction history can be query,please check start and end time.
S-EVR-00150 = The agent is in blacklist
S-EVR-00151 = No agent evoucher found to deduct.
S-EVR-00152 = Agent evoucher is not enought to deduct.
S-EVR-00153 = The ET Transaction is exist.