JL-RES-00001= Fail to delete the journal account, because it has journal account pair.
JL-RES-00002 = Fail to delete the journal rule, because it has journal rule Detail.
JL-RES-00003 = Fail to delete the journal rule deail, because it has journal rule Detail condition.
JL-RES-00004 = Fail to delete the journal rule deail condition, because it has journal rule Detail condition Value.
JL-RES-00005 = Fail to delete the journal account pair, because it has used in journal rule.