JOBSERVERMGR.ABANDONED=Obsolete, please use the new UI
JOBSERVERMGR.CONNECTION_INFO=Connection Infomation
JOBSERVERMGR.ADD_NEW_CONNECTION=New Connection
JOBSERVERMGR.CONNECTION=Connection
JOBSERVERMGR.REMOVE=Remove
JOBSERVERMGR.HOST=Host IP
JOBSERVERMGR.PORT=Port
JOBSERVERMGR.USER_NAME=User Name
JOBSERVERMGR.PASSWORD=Password
JOBSERVERMGR.CONNECT=Connect
JOBSERVERMGR.CANCEL=Cancel
JOBSERVERMGR.SCHEDULER=Scheduler
JOBSERVERMGR.SCHEDULER_NAME=Scheduler Name
JOBSERVERMGR.DETAIL=Detail
JOBSERVERMGR.STANDBY=Standby
JOBSERVERMGR.SHUTDOWN=Shutdown
JOBSERVERMGR.START=Start
JOBSERVERMGR.STARTED=Started
JOBSERVERMGR.JOBS=Jobs
JOBSERVERMGR.JOB_GROUP=Job Group
JOBSERVERMGR.PAUSE_JOB_GROUP=Pause Group
JOBSERVERMGR.RESUME_JOB_GROUP=Resume Group
JOBSERVERMGR.ADD=Add
JOBSERVERMGR.DELETE=Delete
JOBSERVERMGR.ADD_JOB=Add
JOBSERVERMGR.DELETE_JOB=Delete
JOBSERVERMGR.COPY_JOB=Copy
JOBSERVERMGR.TRIGGER_JOB=Trigger Job
JOBSERVERMGR.TRIGGERS=Triggers
JOBSERVERMGR.PAUSE=Pause
JOBSERVERMGR.RESUME=Resume
JOBSERVERMGR.UNSCHEDULER=Unscheduler
JOBSERVERMGR.SHCEDULER_INSTANCE_ID=Scheduler Instance Id:
JOBSERVERMGR.SHCEDULER_NAME=Name:
JOBSERVERMGR.JOBSTORE_CLASS_NAME=Job Store:
JOBSERVERMGR.SCHEDULER_NODE=Node:
JOBSERVERMGR.STANDBY_MODE=Standby Mode:
JOBSERVERMGR.IS_STARTED=Started:
JOBSERVERMGR.THREAD_POOL=Thread Pool:
JOBSERVERMGR.THREAD_POOL_SIZE=Thread Pool Size:
JOBSERVERMGR.VERSION=Version:
JOBSERVERMGR.SCHEDULER_DETAIL=Scheduler Details
JOBSERVERMGR.STATE_LABEL=State:
JOBSERVERMGR.NO_SCHEDULER_FOUND=There are no useful schedulers be found on the jxm server.
JOBSERVERMGR.SURE_TO_SHUTDOWN_SCHEDULER=Are you sure to shutdown the selected scheduler?
JOBSERVERMRG.JOB_NAME=Job Name
JOBSERVERMRG.JOB_GROUP=Job Group
JOBSERVERMRG.NAME=Name
JOBSERVERMGR.GROUP=Group
JOBSERVERMGR.ALL_GROUP=All Group
JOBSERVERMGR.JOB_CLASS=Job Class
JOBSERVERMGR.NEX_FIRE_TIME=Next Fire Time
JOBSERVERMGR.DESCRIPTION=Description
JOBSERVERMGR.JOB_DESCRIPTION=Job Description
JOBSERVERMGR.TRIGGER_DESCRIPTION=Trigger Description
JOBSERVERMGR.JOB_DETAIL=Job Detail
JOBSERVERMGR.JOB_DATA=Job Data
JOBSERVERMGR.KEY=Key
JOBSERVERMGR.VALUE=Value
JOBSERVERMGR.SURE_TO_DELETE_JOB=Are you sure to delete the selected job?
JOBSERVERMGR.ADD_JOB=Add Job
JOBSERVERMGR.USER_BUSINESS_CLASS=User Business Class
JOBSERVERMGR.CONCURRENT=Concurrent
JOBSERVERMGR.BUSINESS_CLASS_NAME=Business Class Name
JOBSERVERMGR.METHOD_NAME=Method Name
JOBSERVERMGR.CLASS_NAME=Class Name
JOBSERVERMGR.SUCCEED_IN_ADD_JOB=Succeed in adding job to the job server.
JOBSERVERMGR.YES=Yes
JOBSERVERMGR.NO=No
JOBSERVERMGR.METHOD_PARAMETERS=Method Parameters
JOBSERVERMGR.ADD_JOB_DATA=Add Job Data
JOBSERVERMGR.EDIT_JOB_DATA=Modify Job Data
JOBSERVERMGR.ADD_METHOD_PARAMETER=Add Method Parameter
JOBSERVERMGR.EDIT_METHOD_PARAMETER=Modify Method Parameter
JOBSERVERMGR.ADD_TRIGGER_SAME_TIME=Add Trigger At The Same Time
JOBSERVERMGR.TRIGGER_NAME=Trigger Name
JOBSERVERMGR.TRIGGER_GROUP=Trigger Group
JOBSERVERMGR.TRIGGER_TYPE=Trigger Type
JOBSERVERMGR.SIMPLE_TYPE=Simple
JOBSERVERMGR.CORN_TYPE=Corn
JOBSERVERMGR.START_TIME=Start Time
JOBSERVERMGR.END_TIME=End Time
JOBSERVERMGR.REPEAT_COUNT=Repeat Count
JOBSERVERMGR.REPEAT_INDEFINITELY=Indefinitely
JOBSERVERMGR.REPEAT_INTERVAL=Repeat Interval
JOBSERVERMGR.CORN_EXPRESSION=Corn Expression
JOBSERVERMGR.STATE=State
JOBSERVERMGR.ADD_TRIGGER=Add Trigger
JOBSERVERMGR.PREVIOUS_FIRE_TIME=Previous Fire Time
JOBSERVERMGR.SUCCEED_REMOVE_TRIGGER=Succeed in unscheduling the trigger.
JOBSERVERMGR.SUCCEED_RESUME_TRIGGER=Succeed in resuming the trigger.
JOBSERVERMGR.SUCCEED_PAUSE_TRIGGER=Succeed in pausing the trigger.
JOBSERVERMGR.SUCCEED_PAUSE_TRIGGER_IN_GROUP=Succeed in pausing triggers in the group.
JOBSERVERMGR.SUCCEED_RESUME_TRIGGER_IN_GROUP=Succeed in resuming triggers in the group.
JOBSERVERMGR.SUCCEED_STANDBY_SCHEDULER=Succeed in pausing the scheduler.
JOBSERVERMGR.SUCCEED_STANDBY_SCHEDULER=Succeed in pausing the scheduler.
JOBSERVERMGR.SUCCEED_START_SCHEDULER=Succeed in starting the scheduler.
JOBSERVERMGR.SUCCEED_IN_TRIGGER_JOB=Succeed in trigging the job.
JOBSERVERMGR.SUCCEED_IN_DELETE_JOB=Succeed in deleting the job.
JOBSERVERMGR.COPY_JOB_DETAIL=Copy Job
JOBSERVERMGR.SUCCEED_IN_COPY_JOB=Succeed in copying the job.
JOBSERVERMGR.SURE_TO_PAUSE_JOB_IN_GROUP=Are you sure to pause the jobs in this group?
JOBSERVERMRG.SUCCEED_IN_PAUSE_JOB_BY_GROUP=Succeed in pausing jobs in the group.
JOBSERVERMRG.SUCCEED_IN_RESUME_JOB_BY_GROUP=Succeed in resuming jobs in the group.
JOBSERVERMRG.JMX_PORT=JMX Port
JOBSERVERMRG.RMI_PORT=RMI Port
JOBSERVERMGR.SURE_TO_REMOVE_TRIGGER=Are you sure to remove the trigger?
JOBSERVERMGR.SUCCEED_IN_ADD_TRIGGER=Succeed in adding the trigger.
JOBSERVERMGR.RMI_SERVICE_NAMING=RMI Service Naming
JOBSERVERMGR.TRIGGER_MONITOR=Trigger Monitor
JOBSERVERMGR.JOB_MONITOR=Job Monitor
JOBSERVERMGR.PAUSE_TRIGGER_GROUP=Pause Group
JOBSERVERMGR.RESUME_TRIGGER_GROUP=Resume Group
JOBSERVERMGR.RUNNING_STATE=Running
JOBSERVERMGR.COMPLETED_STATE=Completed
JOBSERVERMGR.NONE_STATE=Not Exists
JOBSERVERMGR.NORMAL_STATE=Normal
JOBSERVERMGR.PAUSED_STATE=Paused
JOBSERVERMGR.ERROR_STATE=Error
JOBSERVERMGR.BLOCKED_STATE=Blocked
JOBSERVERMGR.FIRE_TIME=Fire Time
JOBSERVERMGR.JOB_RUN_TIME=Run Time(ms)
JOBSERVERMGR.RUNNING_STATE=Running
JOBSERVERMGR.COMPLETED_STATE=Completed
JOBSERVERMGR.VIEW_STATE=View State
JOBSERVERMGR.ALL_JOBS=All Jobs
JOBSERVERMGR.AUTO_FRESH=Automatic Refresh
JOBSERVERMGR.FRESH_FREQUENCY=Frequency/Second
JOBSERVERMGR.FRESH_NOW=Fresh Now
JOBSERVERMGR.JOB_GROUP_NOT_NULL=Please input the job group.
JOBSERVERMGR.TRIGGER_GROUP_NOT_NULL=Please input the trigger group.
JOBSERVERMGR.JOB_GROUP_MAX_LENGTH=The length of job group is greater than the maximum length of {0} character(s). Please input again.
JOBSERVERMGR.TRIGGER_GROUP_MAX_LENGTH=The length of trigger group is greater than the maximum length of {0} character(s). Please input again.
JOBSERVERMGR.PARAM_TYPE_STRING=String
JOBSERVERMGR.PARAM_TYPE_INTEGER=Integer
JOBSERVERMGR.PARAM_TYPE_Long=Long
JOBSERVERMGR.PARAM_TYPE_FLOAT=Float
JOBSERVERMGR.PARAM_TYPE_DOUBLE=Double
JOBSERVERMGR.PARAM_TYPE_DATE=Date
JOBSERVERMGR.PARAM_TYPE_DATETIME=DateTime
JOBSERVERMGR.PARAMETER_TYPE=Type
JOBSERVERMGR.AUTOFIRE_ON_SERVER_RESTART=Auto-fire on server restart
JOBSERVERMGR.STMISFIREINSTRUCTION1 = 1 : fire now,only used on no-repeat job
JOBSERVERMGR.STMISFIREINSTRUCTION2 = 2 : fire now with existing repeat count
JOBSERVERMGR.STMISFIREINSTRUCTION3 = 3 : fire now with remaining repeat count 
JOBSERVERMGR.STMISFIREINSTRUCTION4 = 4 : fire next with remaining repeat count 
JOBSERVERMGR.STMISFIREINSTRUCTION5 = 5 : fire next with existing repeat count
JOBSERVERMGR.CTMISFIREINSTRUCTION1 = 1 : fire once now,then fire with original plan
JOBSERVERMGR.CTMISFIREINSTRUCTION2 = 2 : do noting , fire with original plan
JOBSERVERMGR.MISFIRE=Misfire Policy
JOBSERVERMGR.SET_PARAM=Set Paramter
JOBSERVERMGR.IS_PASS_PARAMS_DYNAMIC= Set Parameter Dynamic
JOBSERVERMRG.IMPORT_FAILED_TIPS = Part of data failed to import,please see the table below.
JOBSERVERMRG.RESULT_INFO = Result Information
JOBSERVERMGR.FAILED_REASON = Failed Reason
JOBSERVERMRG.COVER=Cover