#1451372
CUSTOMERCARE.MARKETING.NOURL = Please set MarketingActivitiesUrl.
CUSTOMERCARE.MARKETING.SELECTMDN = Please select MSISDN first.
CUSTOMERCARE.MARKETING.ACTIVITES.DETAIL = Marketing Activities Detail
CUSTOMERCARE.MARKETING.ACTIVITES.QUERY = Marketing Activities Query
CUSTOMERCARE.MARKETING.ACTIVITES = Marking Activities
#1458783
CUSTOMERCARE.BIND_SERVICE_NUMBER=Bind Service Number
CUSTOMERCARE.CHANGE_RELATION_BINDING=Change Relation Binding
CUSTOMERCARE.IS_BIND_TERMINATION=The subscriber has been binded with {0}, Terminate the other subscriber together?
#1457562
CUSTOMERCARE.WIFI_MANAGEMENT_BLACKLIST=Wifi Management Blacklist
CUSTOMERCARE.WIFI_MANAGEMENT_JOIN_BLACKLIST_CONFIRM=Are you sure to join wifi Blacklist?
CUSTOMERCARE.WIFI_MANAGEMENT_FREE_BLACKLIST_CONFIRM=Are you sure to remove wifi Blacklist?
CUSTOMERCARE.QUERY_BLACKLIST_ERROR=Fail to query wifi blacklist.
CUSTOMERCARE.JOIN_BLACKLIST_ERROR=Fail to join wifi blacklist.
CUSTOMERCARE.FREE_BLACKLIST_ERROR=Fail to remove wifi blacklist.
CUSTOMERCARE.JOIN_BLACKLIST_SUCCESS=Success to join wifi blacklist.
CUSTOMERCARE.FREE_BLACKLIST_SUCCESS=Success to remove wifi blacklist.

#1455872
BPORTAL.MEMBER_MSISDN = Member MSISDN
BPORTAL.HINT_ACCT_ADD_ONE_CUG=It is not allowed order over one CUG product for a account.
BPORTAL.CUG_MEMBER=CUG Member

#1459492
CUSTOMERCARE.SUBS_NOTES = Subscriber Notes
CUSTOMERCARE.ACTIVE_SUBS_LIST=Active Subscribers
CUSTOMERCARE.INACTIVE_SUBS_LIST=Inactive Subscribers
CUSTOMERCARE.NOTES_LIST=Notes List
CUSTOMERCARE.SEQ=SEQ
CUSTOMERCARE.NOTES=Notes
CUSTOMERCARE.DUPLICATE_CARD_REASON=Duplicate Card Reason

CUSTOMERCARE.ERROR_QUERY_CUST_SUBSLIST=Fail to query subscribers list.
CUSTOMERCARE.HINT_CONTENT_SUCCESS_ADD=It has been added successfully.
CUSTOMERCARE.HINT_CONTENT_SUCCESS_DEL=It has been deleted successfully.
CUSTOMERCARE.HINT_CONTENT_SUCCESS_MOD=It has been modified successfully.
CUSTOMERCARE.HINT_EXCEPTION=An exception occurred.
CUSTOMERCARE.BATCH_REGISER_CUST_INFO=Succeed in batch RegisterCustInfo.\rThe batch number is

#1459414
CUSTOMERCARE.MSISDN = MSISDN
CUSTOMERCARE.COMPLETE_ORDERS = Finished Orders
CUSTOMERCARE.SN = SN
CUSTOMERCARE.ORDER_NBR = Order Number
CUSTOMERCARE.CREATED_DATE = Created Date
CUSTOMERCARE.COMPLETED_DATE = Completed Date
CUSTOMERCARE.OLD_ACCT_NBR= Old Acct Number
CUSTOMERCARE.NEW_ACCT_NBR = New Acct Number
CUSTOMERCARE.UNCOMPLETE_ORDERS = Unfinished Orders
CUSTOMERCARE.BATCH_REGISER_CUST_INFO=Succeed in batch RegisterCustInfo.\rThe batch number is
#1501778
VPNMANAGER.SHORT_NUMBER = Short Number
CUSTOMERCARE.VPN_CODE = Vpn Code
VPNMANAGER.HINT.MODIFY_VPN_SUCCESS = Modify vpn sucessfully.
CUSTINFO.HINT_QRY_NO_RECORD = No record.
#1455751
BPORTAL.BALANCE_SHARE_DETAIL = Balance Share Detail
BPORTAL.CURRENT_BALANCE = Current Balance
BPORTAL.BALANCE_USED = Balance Used
BPORTAL.BALANCE_TYPE = Balance Type
BPORTAL.REAL_BALANCE = Real Balance
BPORTAL.IS_CURRENCy = Is Currency
BPORTAL.VPN_NUMBER = Number
BPORTAL.NUMBER_PREFIX = Prefix
BPORTAL.WO_PRIORITY = Priority
BPORTAL.BALANCE_CONSUME = Consume
BPORTAL.DEPARTMENT = Department
BPORTAL.TEMPLATE_NAME=Template Name
#1508129
CUSTOMERCARE.BATCH_ACTIVATE_SUBS_RETURN=Succeed in batch activate subscribers.\rThe batch number is

#1456160
CUSTOMERCARE.CONSUME_INFO = Consume Information
CUSTOMERCARE.ACCTRESTYPE = AcctResType
CUSTOMERCARE.BALANCE.GLID.ITEM = Balance Share GL ID Item

#1508126
CUSTOMERCARE.BATCH_SIM_CARD_LOST=Succeed in batch SimCardLost.\rThe batch number is
CUSTOMERCARE.BATCH_RELEASE_SIM_CARD_LOST=Succeed in batch ReleaseSimCardLost.\rThe batch number is
#1508128
CUSTOMERCARE.BATCH_SET_CREDIT_LIMIT_RETURN=Succeed in batch set credit limit.\rThe batch number is
CUSTOMERCARE.BATCH_SET_CREDIT_LIMIT=Batch Set Credit Limit
CUSTOMERCARE.NEW_CREDIT_LIMIT=Credit Limit
CUSTOMERCARE.CREDIT_LIMIT_TYPE=New Credit Limit Type
#1506085
CUSTOMERCARE.BATCH_MODIFY_CUST_ATTR_RETURN=Succeed in batch modify customer attribute.\rThe batch number is
CUSTOMERCARE.BATCH_MODIFY_CUST_ATTR=Batch Modify Customer Attribute
CUSTOMERCARE.CUSTOMER_CODE=Customer Code
CUSTOMERCARE.ATTR_CODE=Attr Code
CUSTOMERCARE.VALUE=Value
#1508127
CUSTOMERCARE.BATCH_DEACTIVATE_RELATED_PRODUCT_RETURN=Succeed in batch Dvate Related Product.\rThe batch number is:
CUSTOMERCARE.BATCH_ACTIVE_RELATED_PRODUCT_RETURN=Succeed in batch Active Related Product.\rThe batch number is:
CUSTOMERCARE.BATCH_ACTIVATE_RELATED_PRODUCT=batch Active Related Product
CUSTOMERCARE.BATCH_DEACTIVATE_RELATED_PRODUCT=batch Dvate Related Product
CUSTOMERCARE.OFFER_CODE1=Offer code1
CUSTOMERCARE.OFFER_CODE2=Offer code2
CUSTOMERCARE.OFFER_CODE3=Offer code3
CUSTOMERCARE.OFFER_CODE4=Offer code4
CUSTOMERCARE.OFFER_CODE5=Offer code5
#1508027
CUSTOMERCARE.BATCH_DEACTIVATE_RELATED_PRODUCT_RETURN=Succeed in batch DvateRelatedProduct.\rThe batch number is:
CUSTOMERCARE.BATCH_ACTIVE_RELATED_PRODUCT_RETURN=Succeed in batch ActiveRelatedProduct.\rThe batch number is:
#1525304
CUSTOMERCARE.BATCH_REGISTER_CUST_INFO=Batch Register Customer Information
CUSTOMERCARE.BATCH_ACTIVATE_SUBS=Batch Activate Subscriber
CUSTOMERCARE.BATCH_ACTIVATE_RELATED_PRODUCT=Batch Activate Related Product
CUSTOMERCARE.BATCH_DEACTIVATE_RELATED_PRODUCT=Batch Deactivate Related Product
CUSTOMERCARE.EXP_DATE=Expire Date
#1563496
CUSTINFO.STATE.INACTIVE = Inactive
CUSTINFO.STATE.ACTIVE = Active

CUSTOMERCARE.FIJI.CUST_ORDER_ID=Business Key
CUSTOMERCARE.FIJI.SA_ORDER_ID=Dispatch Order ID
CUSTOMERCARE.NEW_SUBS_PLAN=New Subs Plan

#1745991
CUSTOMERCARE.BATCH_MODIFY_USER_NAME = Batch Modify User Name
CUSTOMERCARE.USER_NAMER = User Name
CUSTOMERCARE.BATCH_ACTIVE_USER_NAMER_RETURN=Succeed in batch Active User Name.\rThe batch number is:

CUSTOMERCARE.BAT_TRANSFER_SUCCESS=Succeed in batch transfer.\rThe batch number is
CUSTOMERCARE.NEW_CUST_CODE=New Cust Code
CUSTOMERCARE.BATCH_TRANSFER=Batch Transfer

#1746835
FIJI.CUSTOMERCARE.COMMENT=Comment
FIJI.CUSTINFO.MODIFY_DATE=Modify Date
FIJI.CUSTINFO.REMARKS=Remarks
FIJI.CUSTINFO.CREDIT_LIMIT_MODIFY_HIS=Modify History
FIJI.SALES.OLD_CREDIT_LIMIT=Old Credit Limit
FIJI.SALES.OLD_EFF_DATE=Old Effective Date
FIJI.SALES.OLD_EXP_DATE=Old Expiry Date
FIJI.CREATED_MAN=Created By

FIJI.CUSTOMERCARE.SO_STATE_A = Enable
FIJI.CUSTOMERCARE.SO_STATE_D = Disable
FIJI.CUSTOMERCARE.SO_SELF_OFFER_ID = SELF_OFFER_ID

FIJI.CUSTOMERCARE.SELF_OFFER_CATG_TYPE = Offer Catg Type
FIJI.CUSTOMERCARE.SELF_OFFER_CATG_NAME = Offer Catg Name

FIJI.CUSTOMERCARE.SELF_OFFER_CATG_ID = Offer Catg Id
FIJI.CUSTOMERCARE.SELF_OFFER_CATG_TYPE_ID = Offer Catg Type Id
FIJI.CUSTOMERCARE.SELF_OFFER_CATG_NAME = Offer Catg Name
FIJI.CUSTOMERCARE.SELF_COMMENTS = Comments
FIJI.CUSTOMERCARE.SELF_OFFER_CATG_CODE = Offer Catg Code
FIJI.CUSTOMERCARE.SELF_EFF_DATE = Eff Date
FIJI.CUSTOMERCARE.SELF_EXP_DATE = Exp Date
FIJI.CUSTOMERCARE.SELF_STATE = State
FIJI.CUSTOMERCARE.SELF_STATE_DATE = State Date
FIJI.CUSTOMERCARE.SELF_CREATED_DATE = Created Date
FIJI.CUSTOMERCARE.SELF_SP_ID = Sp Id
FIJI.CUSTOMERCARE.CONTACT_CHANNEL_ID = Contact Channel Id
FIJI.CUSTOMERCARE.CONTACT_CHANNEL_NAME = Contact Channel Name

FIJI.CUSTOMERCARE.DELETE_SURVEY_SUCCESS = Succeed in deleting the category.
FIJI.CUSTOMERCARE.DELETE_SURVEY_FAILED = Failed in deleting the category.
FIJI.CUSTOMERCARE.SELF_ADD_ERROR = Add Error.
FIJI.CUSTOMERCARE.SOC_EDIT_RESULT = Edit Result.

FIJI.CUSTOMERCARE.SELF_DELETE_SUCCESS = Succeed in deleting the Offer.
FIJI.CUSTOMERCARE.SELF_DELETE_FAILED = Fail to delete the Offer.
FIJI.CUSTOMERCARE.SELF_ADD_ERROR = Self Offer Add Error

FIJI_CUSTOMERCARE.TERMINATION_REASON=Termination Reason
FIJI_CUSTOMERCARE.TERMINATION_DATE=Termiantion Date

CUSTOMERCARE.FIJI.TERMINATION_DATE=Termination Time
CUSTOMERCARE.FIJI.TERMINATION_FEE=Termination Fee
CUSTOMERCARE.FIJI.HARDWARE_CHARGE=Hardware charges

CUSTOMERCARE.FIJI.TERMINATION_FEE_ERR=Termination Fee is invalid!
CUSTOMERCARE.FIJI.HARDWARE_CHARGE_ERR=Hardware charges is invalid!

CUSTOMERCARE.FIJI.CONVERSION_FEE=Conversion Fee

CUSTOMERCARE.FIJI.ONE_WAY_BLOCK_FOR_PECCANCY=One-Way Block For Peccancy
CUSTOMERCARE.FIJI.ONE_WAY_REACTIVATION_FOR_PECCANCY=One-Way Reactivation For Peccancy
CUSTOMERCARE.FIJI.TWO_WAY_BLOCK_FOR_PECCANCY=Two-Way Block For Peccancy
CUSTOMERCARE.FIJI.TWO_WAY_REACTIVATION_FOR_PECCANCY=Two-Way Reactivation For Peccancy
CUSTOMERCARE.FIJI.BATCH_PRODUCT_SUCCESS=Succeed in batch deal.\rThe batch number is
CUSTOMERCARE.FIJI.PROD_BATCH_DEAL=Prod Batch Deal

CUSTOMERCARE.FIJI.SUSPENSION_UNDER_REQUEST=Suspension Under Request
CUSTOMERCARE.FIJI.REACTIVATION_UNDER_REQUEST=Reactivation Under Request

#1786374
FIJI.CUSTOMERCARE.BUSI_MAPPING_ID=Busi Mapping 
FIJI.CUSTOMERCARE.TABLE_NAME=Table Name
FIJI.CUSTOMERCARE.PK_NAME=Pk Name
FIJI.CUSTOMERCARE.PK_VALUE=Pk Value
FIJI.CUSTOMERCARE.MAPPING_COLUMN_NAME=Mapping Column Name
FIJI.CUSTOMERCARE.SOURCE_VALUE=Source Value
FIJI.CUSTOMERCARE.CONTACT_CHANNEL=Contact Channel
FIJI.CUSTOMERCARE.MAPPING_VALUE=Mapping Value


CUSTOMERCARE.FIJI.HINT_TERMINATION_DATE_VALDATE=The termination date should be later than the current date. Please input again.

#1809405
FIJI.CUSTOMERCARE.HINT_PASSWORD_SECURITY_LEVEL_LOW=The security level of new password is low. It should include letters, numbers, and special characters(!@#$%^&,.*).Please input again.
FIJI.CUSTOMERCARE.HINT_PASSWORD_TOO_LONG=The length of {0} should be {1} characters or longer. Please input again.
FIJI.CUSTOMERCARE.HINT_PASSWORD_EQUALS_LEN=The length of {0} should be {1} characters. Please input again.
