cdwhen:
  event:
    - push
    - manual
  branch:
    - development
  commit:
    message:
      exclude:
        - '\[skip ci\]'
        - '\[ci skip\]'
        - '\[no ci\]'
steps:
  - name: build-jar
    image: maven:3.9.9-eclipse-temurin-21
    environment:
      MAVEN_OPTS: "-Dmaven.repo.local=/root/.m2/repository"
      GIT_BASE_URL:
        from_secret: GIT_BASE_URL
      GIT_USERNAME:
        from_secret: GIT_USERNAME
      GIT_TOKEN:
        from_secret: GIT_TOKEN
      GIT_ORGANIZATION:
        from_secret: GIT_ORGANIZATION
    commands:
      - git clone -b development --single-branch https://$${GIT_USERNAME}:$${GIT_TOKEN}@$${GIT_BASE_URL}/$${GIT_ORGANIZATION}/ocs-portal-base.git
      - cd ./ocs-portal-base/
      - mvn clean install -DskipTests|| echo 'Failed to build ocs-base'
      - cd ..
      - git clone -b development --single-branch https://$${GIT_USERNAME}:$${GIT_TOKEN}@$${GIT_BASE_URL}/$${GIT_ORGANIZATION}/ocs-portal-service.git
      - cd ./ocs-portal-service/
      - mvn clean install -DskipTests || echo 'Failed to build ocs-service'
      - cd ..
      - mvn clean install -DskipTests || echo 'Build test Failed'

  - name: cleanup
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose down --rmi all --volumes --remove-orphans || true
    depends_on: [build-jar]

  - name: compose-up
    image: docker:24-cli
    environment:
      SPRING_PROFILES_ACTIVE:
        from_secret: SPRING_PROFILE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "=== BUILD DOCKER IMAGE ==="
      - export SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
      - docker-compose -p sinorita up -d --build
    depends_on: [build-jar]