MSGBT.SURE_TO_DELETE=Are you sure to delete?
MSGBT.HINT_NOT_FIND_SUCCESS_ITEM=No results were found.
MSGBT.HINT_SELECT_ITEM=Please select at least one item.
MSGBT.HINT_SURE_AGREE=Are you sure to approval?
MSGBT.HINT_SURE_REFUSE=Are you sure to disapproval?
MSGBT.HINT_APPROVAL_BULLETIN_SUCCESS=Succeed in auditing the bulletin.
MSGBT.HINT_MOD_SUCCESS=Succeed in modifying the {0}.
MSGBT.HINT_ADD_SUCCESS=Succeed in adding the {0}.
MSGBT.HINT_DEL_SUCCESS=Succeed in deleting the {0}.
MSGBT.HINT_INBOX_RECEIVE_MSG_MAX=Inbox receive messages has reached the maximum number. Please clean up.
MSGBT.HINT_OUTBOX_SEND_MSG_MAX=Outbox to send the message has reached the maximum number. Please clean up.
MSGBT.HINT_SAVE_MESSAGE_SUCESS=Succeed in saving the message.
MSGBT.HINT_SEND_MESSAGE_SUCESS=Succeed in sending the message.
MSGBT.HINT_VIEW_READING_PEOPLE=Note: Double click to view detail of reading people.
MSGBT.SUB_TYPE=Sub Type
MSGBT.TYPE=Bulletin Type
MSGBT.DIRECTORY=Directory
MSGBT.SUB_DIRECTORY=Sub Directory
MSGBT.MESSAGE=Message
MSGBT.BTLISTTREE=Bulletin List
MSGBT.PUBBTLISTTREE=Release Bulletin
MSGBT.AUDBTLISTTREE=Approval Bulletin
MSGBT.BTLEVELLISTTREE=Bulletin Level Management
MSGBT.BTTYPELISTTREE=Bulletin Type Management
MSGBT.BTTEMPLATELISTTREE=Bulletin Template Management
MSGBT.PUBMSGLISTTREE=Message List
MSGBT.INQUIRY=Query
MSGBT.SHORT_MSG=Short Message
MSGBT.VIEW_VIEWER_DETAIL=Note: Double click to view detail of reading people.
MSGBT.NEW=New
MSGBT.EDIT=Edit
MSGBT.DELETE=Delete
MSGBT.ADD=New
MSGBT.OK=OK
MSGBT.SAVE=Save
MSGBT.RESET=Reset
MSGBT.CANCEL=Cancel
MSGBT.BTTYPELIST=Bulletin Type List
MSGBT.BT_LEVEL_LIST=Bulletin Level List
MSGBT.TITLE=Title
MSGBT.CREATED_DATE=Created Time
MSGBT.CREATED_DATE_FROM=Created Time From
MSGBT.CREATED_DATE_TO=Created Time To
MSGBT.LEVEL=Level
MSGBT.LEVEL_NAME=Level Name
MSGBT.TYPE_NAME=Bulletin Type Name
MSGBT.REVIEWER=Approver
MSGBT.FILE_NAME=Attachment Name
MSGBT.FORCE_VIEW=Is Forced Reading
MSGBT.ATTACHMENT=Attachment
MSGBT.FILE_DESC=Attachment Remarks
MSGBT.CONTENT=Content
MSGBT.PUBLISHED_BULLETIN=Bulletin Published
MSGBT.TO=To
MSGBT.RIEW_PEOPLE_NUMBER=Number of Reading People 
MSGBT.RIEW_DEGREE=Views
MSGBT.NEW_MESSAGE=New
MSGBT.NOT_APPROVED_BULLETIN=Disapproved Bulletin
MSGBT.DETAIL=Detail
MSGBT.APPROVAL_BY=Approved
MSGBT.NOT_APPROVED_BY=Disapproved
MSGBT.WAITING_APPROVAL_BULLETIN=Waiting for My Audit
MSGBT.APPROVED_BULLETIN=Audit by Myself
MSGBT.APPROVAL_AGREE=Approved
MSGBT.APPROVAL_REFUSE=Disapproved
MSGBT.BULLETIN=Bulletin
MSGBT.BULLETIN_TYPE=Bulletin Type
MSGBT.BULLETIN_LEVEL=Level
MSGBT.EFFECT_TIME=Effective Time
MSGBT.EXPIRY_TIME=Expiry Time
MSGBT.BULLETIN_TEMPLATE=Bulletin Template
MSGBT.TEMPLATE_NAME=Template Name
MSGBT.BULLETIN_TEMPLATE_NAME=Bulletin Template Name
MSGBT.FORCE_READING=Forced Reading
MSGBT.NOT_FORCE_READING=Not Forced Reading
MSGBT.EMERGENCY=Emergency
MSGBT.PRIORITIES=Priorities
MSGBT.GENERAL=general
MSGBT.RECORD_COLOR=Record Color
MSGBT.ICON_URL=Record Icon
MSGBT.CLEAR=Clear
MSGBT.NEW_TYPE=New Type
MSGBT.NEW_SUB_TYPE=New Sub Type
MSGBT.BULLETIN_TEMPLATE_LIST=Bulletin Template List
MSGBT.COMMENTS=Description
MSGBT.MSG_MGR=Message Management
MSGBT.INBOX=Inbox
MSGBT.OUTBOX=Outbox
MSGBT.DRAFTBOX=Drafts
MSGBT.DEFAULT_INBOX=Default Inbox
MSGBT.INBOX_DIRECTORY=Inbox Directory
MSGBT.DIRECTORY_NAME=Directory Name
MSGBT.NEW_DIRECTORY=New Directory
MSGBT.NEW_SUB_DIRECTORY=New Sub-directory
MSGBT.SENDER=Sender
MSGBT.ADDRESSEE=Receiver
MSGBT.CC=Attach Staff
MSGBT.REPLY=Reply
MSGBT.REPLY_ALL=Reply All
MSGBT.FORWARD=Forward
MSGBT.REFRESH=Refresh
MSGBT.STATE=State
MSGBT.EMAIL=Email
MSGBT.COLON=:
MSGBT.BT_TEMPLATE_DEF=Bulletin Template Definition
MSGBT.TEMPLATE_DESC=Template Description
MSGBT.RECEIVER_LIST=Receiver List
MSGBT.RECEIVER=Receiver
MSGBT.NAME=Name
MSGBT.CODE=Code
MSGBT.STAFF=Staff
MSGBT.ORGANIZATION=Organization
MSGBT.MSG_TYPE=Type
MSGBT.MSG_MOVE_TIP=Move to....
MSGBT.BULLETIN_CONFIG=Bulletin Configuration
MSGBT.MSG_DIRECTORY_MGR=Inbox Directory Management 
MSGBT.READING_PEOPLE_LIST=Reading People List
MSGBT.NO=No.
MSGBT.UPLOAD=Upload
MSGBT.ADUIT_REASON_WINDOW=Bulletin Audit
MSGBT.ADUIT_REASON=Audit Reason
MSGBT.DISAPPROVED_REASON=Disapproved Reason
MSGBT.RE_PUBLISH=Republish
MSGBT.HINT_RE_PUBLISH_SUCC=Succeed in republishing the bulletin.
MSGBT.HINT_CINFIRM_REPUBLISH=Are you sure to republish?
MSGBT.AUDIT_RESULT=Audit Result
MSGBT.BULLETIN_AUDIT=Bulletin Audit
MSGBT.SEND=Send
MSGBT.MOVE_FOLDERS=Move into Directory
MSGBT.CREATE_FOLDERS=Create Directory
MSGBT.AUDITOR=Auditor
MSGBT.PARTY_CODE=Party Code
MSGBT.PARTY_NAME=Party Name
MSGBT.PARTY_TYPE=Party Type
MSGBT.HINT_MOVE_MESSAGE_SUCESS=Succeed in moving message to {0} directory.
MSGBT.MSG_DIRECTORY_MGT=Inbox Directory Management
MSGBT.HINT_EXPDATE_GE_SYSDATE=Expiry date must be greater than or equal to the current date.
MSGBT.HINT_SEND_MESSAGE_SUCCESS=Succeed in sending message.
MSGBT.HINT_SAVE_MESSAGE_SUCCESS=Succeed in saving message.
MSGBT.BULLETIN_RETRIEVE=[Retrieved]
MSGBT.CREATEDED_BULLETIN=Create By Myself

MSGBT.BFM_MSG_TMPL_TYPE=Message Template Type
MSGBT.BFM_MSG_TMPL_TYPE__TYPE_NAME=Message Template Type Name
MSGBT.BFM_MSG_TMPL__TMPL_NAME=Message Template Name
MSGBT.BFM_MSG_TMPL__TMPL_CONTENT=Message Template Content
MSGBT.BFM_MSG_TMPL__CREATED_DATE=Creation Time
MSGBT.BFM_MSG_TMPL__COMMENTS=Remarks
MSGBT.BFM_MSG_TMPL=Message Templates
MSGBT.BFM_MSG_TMPL_INFO=Message Template Information
MSGBT.MSG_LEVEL=Urgency
MSGBT.EXP_DATE=Failure Time
MSGBT.IS_POPUP=Whether Pop
MSGBT.SEND_TYPE=Transmit Mode
MSGBT.TIME_TO_SEND=Transmission Time
MSGBT.SEND_TYPE_I=Send Now
MSGBT.SEND_TYPE_S=Regularly Send
MSGBT.MESSAGE_CONFIG=Messaging Configuration
MSGBT.MESSAGE_TMPL_MANAGER=Message Template Manager
MSGBT.MESSAGE_TMPL_LEVEL=Message Level Management
MSGBT.SAVE_AS_DRAFT=Save As Draft
MSGBT.PUBLISH=Publish
MSGBT.EFF_DATE_FROM=Effect Time From
MSGBT.EFF_DATE_TO=Effect Time To
MSGBT.EXP_DATE_FROM=Expiry Time From
MSGBT.EXP_DATE_TO=Expiry Time To
MSGBT.CREATOR=Creator
MSGBT.STATE_PUBLISHED=Publish
MSGBT.STATE_AUDITING=Audit
MSGBT.STATE_DRAFT=Draft
MSGBT.STATE_DEL_LOGIC=Logic Delete
MSGBT.STATE_RETRIEVE=Retrieved
MSGBT.STATE_NOT_APPROVED=Not Approved
MSGBT.EXPORT=Export
MSGBT.BULLETIN_READ_RECORDS=Bulletin Read Records
MSGBT.ALL_BULLETIN=All Bulletin
MSGBT.SEARCH=Search
MSGBT.ORG_NAME=Organization Name
MSGBT.READ_COUNT=Read Records
MSGBT.UN_READ_COUNT=Unread Records
MSGBT.BULLETIN_MANAGEMENT=Bulletin Management
MSGBT.BEGIN_TIME_FROM=Create Time From
MSGBT.BEGIN_TIME_TO=Create Time To
MSGBT.EXP_TIME_FROM=Expired Time From
MSGBT.EXP_TIME_TO=Expired Time To
MSGBT.SEND_TIME_FROM=Send Time From
MSGBT.SEND_TIME_TO=Send Time To

INVENTORY.COMPANY=Company
SYSTEM.HINT_SELECT_JOB=Please select a staff job.
SYSTEM.HINT_SELECT_ORG=Please select an organization.
SYSTEM.HINT_SELECT_STAFF=Please select a staff.
SYSTEM.STAFF_AND_COMPANY=Staff and Company
SYSTEM.STAFF_CODE=Staff Code
SYSTEM.STAFF_JOB=Job Name
SYSTEM.STAFF_JOB_ID=Staff Job ID
SYSTEM.STAFF_NAME=Staff Name
MSGBT.READ=Read
MSGBT.UN_READ=Unread
BUSIORDER.RULE.ORDER_AUTHOR = Creator