#Created by JInto - www.guh-software.de
#Fri Dec 14 14:13:25 CST 2012
PUBLICRULE.APPLY_MODULE=Apply Module
PUBLICRULE.DISPATCH_ORDER_TYPE=Apply Module
PUBLICRULE.DOUBLE_CLICK_TIP=Note\: Double click for detail.
PUBLICRULE.FAC_CODE=Factor Code
PUBLICRULE.FAC_NAME=Factor Name
PUBLICRULE.FAC_TYPE=Factor Type
PUBLICRULE.FAC_TYPE_DATE=Date
PUBLICRULE.FAC_TYPE_MUL_SEL=Multi Select
PUBLICRULE.FAC_TYPE_RANGE=Between
PUBLICRULE.FAC_TYPE_SINGLE_SEL=Single Select
PUBLICRULE.FAC_TYPE_TEXT=Text
PUBLICRULE.FIX_VALUE=Fixed Value
PUBLICRULE.HINT_PLEASE_SELECT_NODE=Please select a node.
PUBLICRULE.INPUT_VALUE=Input Value
PUBLICRULE.OBJECT_VALUE=Object Value
PUBLICRULE.OBJ_NAME=Object Name
PUBLICRULE.OPERATOR=Operator
PUBLICRULE.REMARKS=Remarks
PUBLICRULE.RULE_COND_CL_VAL=Factor Value
PUBLICRULE.RULE_DETAIL=Rule Detail
PUBLICRULE.RULE_FACTOR=Rule Factor Item
PUBLICRULE.RULE_FAC_ITEM_EDIT=Rule Factor Item Edit
PUBLICRULE.RULE_FAC_OBJECT=Rule Factor Object Library
PUBLICRULE.RULE_NAME=Rule Name
PUBLICRULE.RULE_SCRIPT=Rule Script
PUBLICRULE.RULE_TPL=Rule Template
PUBLICRULE.RULE_TPL_DETAIL=Rule Template Detail
PUBLICRULE.RULE_TPL_NAME=Rule Template Name
PUBLICRULE.RULE_TPL_TYPE=Rule Template Type
PUBLICRULE.RULE_TYPE=Rule Type
PUBLICRULE.SEARCH_RULE_TPL=Search Rule Template
PUBLICRULE.SERV=Service
PUBLICRULE.SERVICE_DESC=Service Description
PUBLICRULE.SERVICE_NAME=Object Name
PUBLICRULE.SERVICE_TYPE=Service Type
PUBLICRULE.SERV_NAME=Runtime Object
PUBLICRULE.SQL=SQL
PUBLICRULE.SQL_VALUE=Execute SQL
PUBLICRULE.SRC_VALUE_TYPE=Value Type
PUBLICRULE.SVC_NAME=Service Name
