S-CNCT-00001=Subscriber[{0}] is inactive and advice can not be sent.
S-CNCT-00002=Subscriber[{0}] is terminated and advice can not be sent.
S-CNCT-00003=Subscriber[{0}] is blocked for overdue and advice can not be sent.
S-CNCT-00004=Subscriber[{0}] is terminated for overdue and advice can not be sent.
S-CNCT-00005=Subscriber[{0}] is Non-provisioning and advice can not be sent
S-CNCT-00006=The state of Subscriber[{0}] is error and advice can not be sent.
S-CNCT-00007=Fail to create advice of batch contact instance.