#Created by JInto - www.guh-software.de
#Thu Aug 15 13:39:34 CST 2013
BPORTAL-BCMEMBER-00001=Fail to check, because the short number already exists in this cust.
BPORTAL-BCMEMBER-00002=Fail to check, because the member type is OM(Owner Member).
BPORTAL-BCMEMBER-00003=Fail to check, because the subscriber already exists in this account.
BPORTAL-BCMEMBER-00004=Fail to check, because the member type is the same as the old one.
BPORTAL-BCMEMBER-00005=Fail to check, because PM(Private Member) can not be added default balance share.
BPORTAL-BCMEMBER-00006=Fail to check, because the member does not exist.

BPORTAL-S-SALES-00001={0} could not be ordered, because the customer already has a vpn product.
BPORTAL-S-SALES-00002={0} could not be ordered, because the customer has an uncompleted vpn order.