J-JOBSERVERMGR-0001=Fail to get job group name list.
J-JOBSERVERMGR-0002=Fail to get job name in group {0}.
J-JOBSERVERMGR-0003=Fail to get job detail which name is {0} in group {1}.

J-JMX-IP-NULL=The ip address of jmx server can not be empty.
J-JMX-PORT-NULL=The port of jmx server can not be empty.
J-JMX-PORT-FORMAT-ERROR=The port format is error. The jmx server port must be an positive integer.

J-RMI-IP-NULL=The ip address of rmi server can not be empty.
J-RMI-PORT-NULL=The port of rmi server can not be empty.
J-RMI-PORT-FORMAT-ERROR=The port format is error. The rmi server port must be an positive integer.
J-RMI-SERVICENAMING-NULL=The SericeNaming of rmi server can not be empty.

J-JMX-01=Fail to get attribute {0} from the job server which object name is {1}.
J-JMX-02=Jobserver system error\,please contact the system administrator.

J-JMX-SCHEULDER-01=Fail to get scheduler in job server which ip is {0} and port is {1}.
J-JMX-SCHEULDER-02=The scheduler with object name "{0}" is not exist in job server which ip is {1} and port is {2}.
J-JMX-SCHEULDER-03=There are no useful schedulers in the job server which ip is {0} and port is {1}.
J-JMX-SCHEULDER-04=Fail to connect the job server which ip is {0} and port is {1}\,please check the ip and port\,the port is set by the JOB_JMX_PORT in file setbosstoolenv.sh.
J-JMX-JOB-GROUP-01=There are no useful job groups in the scheduler in job server which ip is {0} and port is {1} with object name {2} 

J-RMI-01=Fail to connect the rmi server which ip is {0}, port is {1} and service naming is {2}.
J-RMI-02=Fail to execute method {0} in the class {1} on the rmi server. 
J-RMI-03=Fail to execute the rmi method, because the parameter action is not an realization of com.ztesoft.zsmart.jobservices.cmd.Action.

J-REFLECT-01=Fail to get the instance of class {0}.
J-REFLECT-02=Fail to invoke the method {0} in class {1}.
J-REFLECT-03=Class {0} was not found in the system.
J-REFLECT-04=Method {0} was not found in the class {1}.
J-REFLECT-05=No privilege to visit the method {0} in the class {0}.
J-REFLECT-06=No Constructor was not found in the class {0}.
J-REFLECT-07=No privilege to visit the Constructor in the class {0}.
J-REFLECT-08=No method {0} was found in class {1} with the given parameter types.

J-JOB-HAS-EXIST=Fail to add Job with name: {0} and group: {1}, because one already exists with this identification.
J-TRIGGER-HAS-EXIST=Fail to add trigger with name: {0} and group: {1}, because one already exists with this identification.