S-CNT-00001=Subscribe[{0}] is inactive and advice can not be sent.
S-CNT-00002=Subscribe[{0}] is terminated and advice can not be sent.
S-CNT-00003=Subscribe[{0}] is blocked for overdue and advice can not be sent.
S-CNT-00004=Subscribe[{0}] is terminated for overdue and advice can not be sent.
S-CNT-00005=Subscribe[{0}] is provisioning and advice can not be sent
S-CNT-00006=The state of subscribe[{0}] is error and advice can not be sent.
S-CNT-00007=Fail to create advice of batch contact instance.